
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Vehiculo</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del vehiculo</div>   
<div class="panel-body">
    <form id="tra">
     <div class="row">
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombre de la Placa</label>           
      <input type="text" class="form-control" id="placa" name="placa"> 
      </div>    
      </div>
       </div>   
       <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Descripción</label>           
      <input type="text" class="form-control"  id="descri" name="descri"> 
      </div>    
      </div>    
    </div> 
      <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">tipo_vehiculo</label>           
      <select class="form-control" id="vehi" name="vehi" style="cursor:pointer;">
      <option>Gasolina</option>
      <option>Diesel</option>   
      <option>Gas</option> 
       </select> 
      </div>    
      </div>    
    </div> 
        <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Estado Vehiculo</label>           
      <select class="form-control" id="estado" name="estado" style="cursor:pointer;">
      <option>Carro Nuevo</option>
      <option>Carros Viejo</option>
      <option>Carro Bueno</option>   
      <option>Carro Regular</option> 
       </select> 
      </div>    
      </div>    
    </div> 
     <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Capacidad de Pasajeros</label>           
      <input type="text" class="form-control"  id="pasa" name="pasa"> 
      </div>    
      </div>    
    </div> 
    </form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
