        <br>
        <a href="/practicas/listarpractica">
        <button type="button"  class="btn btn-success">Atrás
        <span class="glyphicon glyphicon-arrow-right"></span></button></a>
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Liquidar Docente</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Liquidación de la Práctica</div>   
<div class="panel-body">  
<form id="res">
<div class="row"> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">viatico docente</label>           
      <input  type="text" class="form-control" id="via" name="via"> 
      </div>    
      </div> 
     <div class="col-lg-6"> 
     <div class="form-group">
     <label for="input" class="">Auxilio Estudiante</label>           
     <input  type="text" class="form-control" id="estu" name="estu"> 
      </div>    
      </div> 
 </div>
    <div class="row"> 
        <br>
      <div class="col-lg-6">   
      <div class="form-group">
      <label for="input" class="">Transporte Especial</label>           
      <input  type="text" class="form-control" id="tran" name="tran"> 
      </div>    
      </div> 
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Estado Pago</label>           
      <select class="form-control" id="estado" name="estado" style="cursor:pointer;">
          <option>Tramite</option> 
          <option>pagada</option> 
          <option>Cancelada la Práctica</option>    
       </select> 
      </div>    
      </div>   
      </div> 
  
 <!--   <div class="row">
        <br>
     <label class="center-block" align="center">Transporte Especial</label>   
    </div> -->
     <div class="row"> 
        <br>
      <div class="col-lg-6">  
      <div class="form-group">
      <label for="input" class="">Fecha Pago</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="pa" name="pa" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>   
      </div>
      <div class="col-lg-6">  
     <div class="form-group">
     <label for="input" class="">Legalizado</label>           
      <select class="form-control" id="lega" name="lega" style="cursor:pointer;">
      <option>Si</option> 
      <option>No</option> 
      </select> 
      </div>    
      </div>       
      </div>
    <div class="row">   
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">Fecha Legalizado</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="le" name="le" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>   
      </div>   
    </div>    
</form>   
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="button" value="Liquidar" id="agregar" class="btn btn-default"  />
     <br>
     <br>
   </div>          
   </div>  
</div>
</div>
