
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Viaticos</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Liquidación de la Práctica</div>   
<div class="panel-body">  
<form id="res">
<div class="row"> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">Nombre completo del docente</label>           
      <select class="form-control" id="do" name="do" style="cursor:pointer;">
          <?php foreach ($this->participantes as $participantes) {?>
          <option  value="<?php echo $participantes['id_participante'];?>"><?php echo $participantes['nombre'];?></option> 
           <?php }?> 
       </select>
      </div>    
      </div> 
     <div class="col-lg-6"> 
     <div class="form-group">
     <label for="input" class="">Identificación</label>           
      <select class="form-control" id="iden" name="iden" style="cursor:pointer;">
          <?php foreach ($this->participantes as $participantes) {?>
          <option  value="<?php echo $participantes['id_participante'];?>"><?php echo $participantes['identificacion'];?></option> 
           <?php }?> 
     </select>
      </div>    
      </div> 
 </div>
   
  <!--   <div class="row"> 
        <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Sueldo Básico</label>           
      <input  type="text" class="form-control" id="codigo" name="codigo"> 
      </div>    
      </div> 
    </div> -->
    <div class="row"> 
        <br>
      <div class="col-lg-6">   
      <div class="form-group">
      <label for="input" class="">Días Pernoctados</label>           
      <input  type="text" class="form-control" id="pernoc" name="pernoc"> 
      </div>    
      </div> 
      <div class="col-lg-6">   
      <div class="form-group">
      <label for="input" class="">Auxilio del Estudiante</label>            
      <input  type="text" class="form-control" id="estu" name="estu"> 
      </div>    
      </div>   
    </div> 
  <!--   <div class="row">
        <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Modalidad de Contratación</label>           
      <input  type="text" class="form-control" id="grupo" name="grupo"> 
      </div>    
      </div> 
    </div> -->
    <div class="row">
        <br>
     <label class="center-block" align="center">Transporte Especial</label>   
    </div>
     <div class="row">
         <br>
        <div class="col-xs-6">
        <div class="form-group">
        <label> Tipo</label>
        <select class="form-control" id="tipo" name="tipo" style="cursor:pointer;">
          <?php foreach ($this->recursos as $recursos) {?>
        <option  value="<?php echo $recursos['id_recursos'];?>"><?php echo $recursos['nombre'];?></option> 
           <?php }?> 
     </select>
        </div>
        </div>
        <div class="col-xs-6">
        <div class="form-group">
        <label> valor($)</label>
         <select class="form-control" id="valor" name="valor" style="cursor:pointer;">
          <?php foreach ($this->progrecursos as $progrecursos) {?>
          <option  value="<?php echo $progrecursos['id_pro'];?>"><?php echo $progrecursos['valor'];?></option> 
           <?php }?> 
        </select>
        </div>
        </div>    
        </div>
<!--    <div class="row">
        <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Ruta</label>           
      <input  type="text" class="form-control" id="ru" name="ru"> 
      </div>    
      </div> 
    </div> -->
    <div class="row">
        <br>
      <div class="col-lg-6">  
      <div class="form-group">
      <label for="input" class="">Fecha Pago</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="ini" name="ini" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>   
      </div> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">Fecha Legalizado</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="ini" name="ini" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>   
      </div>     
     </div>
      
    <div class="row">
     <div class="col-lg-6">    
     <div class="form-group">
     <label for="input" class="">Estado Pago</label>           
      <select class="form-control" id="estado" name="estado" style="cursor:pointer;">
          <option>Tramite</option> 
          <option>pagada</option> 
          <option>Cancelada la Práctica</option>    
       </select> 
      </div>    
      </div> 
       <div class="col-lg-6">  
       <div class="form-group">
       <label for="input" class="">Legalizado</label>           
      <select class="form-control" id="estado" name="estado" style="cursor:pointer;">
      <option>Pago Realizado</option> 
      <option>Pago Sin Realizar</option> 
       </select> 
      </div>    
      </div>   
    </div>
   
     <div class="row"> 
        <br>
      <div class="col-md-4"> 
      <div class="form-group">
      <label for="input" class="" align="center">Liquidar Docente</label> 
      <div class="">
        <input type='button' class="button btn btn-default"  value='Calcular Viatico' data-toggle="modal" data-target="#myModal1" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel1">Digite los datos para la liquidar al docente,  </h4>
         </div>
        <div class="modal-body"  style="text-align: center">
        <div class="form-group">
         
        <label class="form-group"> Escala Y Lugar</label>
        <select class="form-control" name="escala" id="escala" style="cursor:pointer;">
        <option>Ayapel</option>
        <option>Buenavista</option>
        <option>Canalete</option>
        <option>Cereté</option>
        <option>Chimá</option>
        <option>Chinú</option>
        <option>Cienaga de Oro</option>
        <option>Cotorra</option>
        <option>La Apartada</option>
        <option>Loríca</option>
        <option>Los Córdobas</option>
        <option>Momíl</option>
        <option>Moñitos</option>
        <option>Montelibano</option>
        <option>Mónteria</option>
        <option>Planeta Rica</option>
        <option>Puerto Escondido</option>
        <option>Puerto Libertador</option>
        <option>Pueblo Nuevo</option>
        <option>Purisima</option>
        <option>Sahagún</option>
        <option>San Andrés de Sotavento</option>
        <option>San Antero</option>
        <option>San Bernardo del Viento</option>
        <option>San Carlos</option>
        <option>San Jose de Uré</option>
        <option>San Pelayo</option>
        <option>Tierralta</option>
        <option>Tuchín</option>
        <option>Valencia</option>
        <option>Otros Municipios</option>
        </select> 
         <br>
         <br>
        <label class="form-group"> valor Diario</label>
        <select id="equiva" name="equiva" class="form-control"  style="cursor:pointer;">
        <option>0.15</option>  
        <option>0.23</option> 
        </select>    
         <br>
         <label class=""> Días Pernoctados </label> 
        <select class="form-control" name="per" id="per" style="cursor:pointer;">
        <option>0</option>
        <option>0.5</option>
        <option>1.0</option>
        <option>1.5</option>
        <option>2.0</option>
        <option>2.5</option>
        <option>3.0</option>
        <option>3.5</option>
        <option>4.0</option>
        <option>4.5</option>
        <option>5.0</option>
        <option>5.5</option>
        <option>6.0</option>
        <option>6.5</option>
        <option>7.0</option>
        <option>7.5</option>
        <option>8.0</option>
        <option>8.5</option>
        <option>9.0</option>
        <option>9.5</option>
        <option>10</option>
        <option>10.5</option>
        <option>11.0</option>
        <option>11.5</option>
        <option>12.0</option>
        <option>12.5</option>
        <option>13.0</option>
        <option>13.5</option>
        <option>14.0</option>
        <option>14.5</option>
        <option>15.0</option>
        <option>15.5</option>
        <option>16.0</option>
        <option>16.5</option>
        <option>17.0</option>
        <option>17.5</option>
        <option>18.0</option>
        <option>18.5</option>
        <option>19.0</option>
        <option>19.5</option>
        <option>20.0</option>
        <option>20.5</option>
        <option>21.0</option>
        <option>21.5</option>
        <option>22.0</option>
        <option>22.5</option>
        <option>23.0</option>
        <option>23.5</option>
        <option>24.0</option>
        <option>25.5</option>
        <option>26.0</option>
        <option>26.5</option>
        <option>27.0</option>
        <option>27.5</option>
        <option>28.0</option>
        <option>28.5</option>
        <option>29.0</option>
        <option>29.5</option>
        <option>30.0</option>
        <option>30.5</option>
        </select>       
         <br>
        <label class="form-group"> Equivalencia </label>
        <select id="equiva" name="equiva" class="form-control"  style="cursor:pointer;">
        <option>103.418</option>  
        <option>158.574</option> 
        </select>
        <br>
         Esta Seguro de Calcular el Viatico del Docente
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agreg" data-dismiss="modal" class="btn btn-default"> Calcular</button>
        </div>
        </div>
        </div>
        </div>
        </div>         
      </div>
      </div>    
      </div> 
    <div class="row">
     <div class="col-md-5">
        <div class="text-right">
        <div class="list-inline">
        <label>Liquidar Estudiante</label>          
        </div>      
        <input type='button' class="button btn btn-default"  value='Calcular Viatico' data-toggle="modal" data-target="#myModal2" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2">Digite los datos, Para liquidar a los estudiantes  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
        <div class="list-inline">
         <label class=""> Numero de Estudiantes </label>        
         </div>
         <input type='text'  placeholder="Digite el Campo " id="es" name="es"/> 
         <br>
         <br>
          <label class=""> Días Pernoctados </label> 
        <select class="form-control" name="perno" id="perno" style="cursor:pointer;">
        <option>0</option>
        <option>0.5</option>
        <option>1.0</option>
        <option>1.5</option>
        <option>2.0</option>
        <option>2.5</option>
        <option>3.0</option>
        <option>3.5</option>
        <option>4.0</option>
        <option>4.5</option>
        <option>5.0</option>
        <option>5.5</option>
        <option>6.0</option>
        <option>6.5</option>
        <option>7.0</option>
        <option>7.5</option>
        <option>8.0</option>
        <option>8.5</option>
        <option>9.0</option>
        <option>9.5</option>
        <option>10</option>
        <option>10.5</option>
        <option>11.0</option>
        <option>11.5</option>
        <option>12.0</option>
        <option>12.5</option>
        <option>13.0</option>
        <option>13.5</option>
        <option>14.0</option>
        <option>14.5</option>
        <option>15.0</option>
        <option>15.5</option>
        <option>16.0</option>
        <option>16.5</option>
        <option>17.0</option>
        <option>17.5</option>
        <option>18.0</option>
        <option>18.5</option>
        <option>19.0</option>
        <option>19.5</option>
        <option>20.0</option>
        <option>20.5</option>
        <option>21.0</option>
        <option>21.5</option>
        <option>22.0</option>
        <option>22.5</option>
        <option>23.0</option>
        <option>23.5</option>
        <option>24.0</option>
        <option>25.5</option>
        <option>26.0</option>
        <option>26.5</option>
        <option>27.0</option>
        <option>27.5</option>
        <option>28.0</option>
        <option>28.5</option>
        <option>29.0</option>
        <option>29.5</option>
        <option>30.0</option>
        <option>30.5</option>
        </select>    
         <br>
         <br> 
      <label class="form-group"> Auxilio Estudiante </label>
        <select id="equiva" name="equiva" class="form-control"  style="cursor:pointer;">
        <option>31.025</option>  
        
        </select>
        </div>
         Esta Seguro de Calcular el Viatico del Estudiante
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agrega" data-dismiss="modal" class="btn btn-default"> Calcular </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>        
    </div>   
    </div>
      <div class="row">
      <div class="col-xs-6">     
      <div class="form-group">
      <label for="input">Viatico del Docente</label> 
      <input  type="text" class="form-control" id="doc" name="doc">        
      </div>    
      </div>
      <div class="col-xs-6">    
      <div class="form-group">
      <label for="input">Viatico del Estudiante</label> 
      <input  type="text" class="form-control" id="est" name="est">        
      </div>    
      </div>     
      </div>
</form>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="button" value="Guardar" id="agregar" class="btn btn-default"  />
     <input type="button" value="Cancelar" class="btn btn-danger " /> 
    
   </div>          
   </div>  
</div>
