
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Ruta</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Ruta</div>   
<div class="panel-body">
   <form id="rut">
      <div class="row">
      <div class="col-lg-6"> 
      <div class="form-group">  
      <label for="input" class="">Origen</label>           
      <input type="text" class="form-control" id="ori" name="ori"> 
      </div>    
      </div> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">Destino</label>           
      <input type="text" class="form-control"  id="des" name="des"> 
      </div>    
      </div>
 </div>
    <br>
    <div class="row">
     <div class="col-lg-6">    
    <div class="form-group">  
    <label for="input" class="">Ruta</label>           
    <input type="text" class="form-control" id="ruta" name="ruta"> 
    </div>    
    </div>  
    <div class="col-lg-6">    
    <div class="form-group">  
    <label for="input" class="">Sitio</label>           
     <select class="form-control" id="si" name="si" style="cursor:pointer;">
      <option>Departamento</option>
      <option>Municipio</option>
    </select>   
    </div>    
    </div>      
    </div> 
    <br>    
    </form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
