
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Editar Ruta</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Ruta</div>   
<div class="panel-body">
   <form id="rut">
      <div class="row"> 
      <div class="col-lg-6">    
      <div class="form-group">    
      <label for="input" class="">Origen</label>           
      <input type="text" class="form-control" value="<?php echo $this->rutas[0]['origen'];?>" id="ori" name="ori"> 
      </div>    
      </div> 
      <div class="col-lg-6">   
      <div class="form-group"> 
      <label for="input" class="">Destino</label>           
      <input type="text" class="form-control"  value="<?php echo $this->rutas[0]['destino'];?>" id="des" name="des"> 
      </div>    
      </div>    
 </div>
    <br>
    <div class="row">
     <div class="col-lg-6">
     <div class="form-group">    
      <label for="input" class="">Ruta</label>           
      <input type="text" class="form-control" value="<?php echo $this->rutas[0]['ruta'];?>" id="ruta" name="ruta"> 
      </div>    
      </div>
     <div class="col-lg-6">
      <div class="form-group">    
      <label for="input" class="">Sitio</label>           
      <select class="form-control" id="si" name="si" data-sitio="<?php echo $this->rutas[0]['cod_ruta'];?>" style="cursor:pointer;">
      <?php foreach ($this->rutas as $rutas) {?>
      <option  value="<?php echo $rutas['cod_ruta']; ?>"><?php echo $rutas['sitio']; ?></option>
      <?php }?>
      </select> 
      </div>    
      </div>  
    </div> 
    <br>
  
       
    </form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="hidden" id="cod_ruta" value="<?php echo $this->rutas[0]['cod_ruta'];?>"> 
       <input type="button" id="editar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
