
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Facultad</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Facultad</div>   
<div class="panel-body">
<div class="row">    
    <form id="fac">
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombre de la Facultad</label>           
      <input type="text" class="form-control" id="facultad" name="facultad"> 
      </div>    
      </div> 
    </form>
 </div>  
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
