
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Calendario Académico</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Calendario Académico</div>   
<div class="panel-body">  
<form id="cale">  
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Año</label> 
      <select class="form-control" id="annio" name="annio" style="cursor:pointer;">
      <?php foreach ($this->calendario as $calendario) {?>  
      <option  value="<?php echo $calendario['annio'];?>"><?php echo $calendario['annio'];?></option>
      <?php }?> 
      </select>
      </div>    
      </div>
    
     <div class="text-center">
        <input type='button' class="button btn btn-default"  value='Agregar Año' data-toggle="modal" data-target="#myModal" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Digite el Año,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text' id="annio" name="annio"/>        
        </div>
         Esta Seguro de Agregar el Año
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="annio" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div> 
 </div> 
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Periodo</label>    
      <select class="form-control" id="per" name="per" style="cursor:pointer;">
      <?php foreach ($this->calendario as $calendario) {?>  
      <option  value="<?php echo $calendario['periodo'];?>"><?php echo $calendario['periodo'];?></option>
      <?php }?> 
      </select>
      </div>    
      </div> 
      <div class="text-center">
        <input type='button' class="button btn btn-default"  value='Agregar Periodo' data-toggle="modal" data-target="#myModal1" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel1">Digite el Periodo,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text' id="annio" name="annio"/>        
        </div>
         Esta Seguro de Agregar el Periodo
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="annio" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div> 
 </div> 
    <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Inicio</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="ini" name="ini" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Final</label>           
      <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
      <input type='text' id="fin" name="fin" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div> 
     
 </div> 
</form>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="button" value="Guardar" id="agregar" class="btn btn-default"  />
     <input type="button" value="Cancelar" class="btn btn-danger " /> 
    
   </div>          
   </div>  
</div>


