
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Calendario Académico</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Calendario Académico</div>   
<div class="panel-body">  
<form id="cale">  
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Año</label> 
      <select class="form-control" id="annio" name="annio" style="cursor:pointer;"> 
       <?php foreach ($this->annio as $annio) {?>  
      <option  value="<?php echo $annio['id_annio'];?>"><?php echo $annio['annio'];?></option>
      <?php }?>
      </select>
      </div>    
      </div>
 </div> 
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Periodo</label>    
      <select class="form-control" id="per" name="per" style="cursor:pointer;">
      <?php foreach ($this->periodo as $periodo) {?>  
      <option  value="<?php echo $periodo['id_periodo'];?>"><?php echo $periodo['periodo'];?></option>
      <?php }?>
      </select>
      </div>    
      </div> 
     
 </div> 
    <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Inicio</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="ini" name="ini" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Final</label>           
      <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
      <input type='text' id="fin" name="fin" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div> 
     
 </div> 
</form>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="button" value="Guardar" id="agregar" class="btn btn-default"  />
     <input type="button" value="Cancelar" class="btn btn-danger " /> 
    
   </div>          
   </div>  
</div>


