
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Editar Calendario Académico</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:18px;color:#777"> Datos del Calendario Académico</div>   
<div class="panel-body">  
<form id="cale">  
 <div class="row"> 
     <br>
      <div class="col-lg-6"> 
      <div class="form-group">
      <label style="font-family:aleolight;font-size:14px;color:#000">Año</label> 
      <select class="form-control" id="an" name="an" data-annio="<?php echo $this->calendario[0]['id_annio']['id_annio']; ?>" style="cursor:pointer;">
      <?php foreach ($this->annio as $annio) {?>  
      <option  value="<?php echo $annio['id_annio'];?>"><?php echo $annio['annio'];?></option>
      <?php }?> 
      </select>
      </div>    
      </div>
      <div class="col-lg-6">
      <div class="form-group"> 
      <label style="font-family:aleolight;font-size:14px;color:#000">Periodo</label>    
      <select class="form-control" id="pe" name="pe" data-periodo="<?php echo $this->calendario[0]['id_periodo']['id_periodo'];?>" style="cursor:pointer;">
      <?php foreach ($this->periodo as $periodo) {?>  
      <option  value="<?php echo $periodo['id_periodo'];?>"><?php echo $periodo['periodo'];?></option>
      <?php }?> 
      </select>
      </div>    
      </div>
 </div> 
     <div class="row"> 
  <div class="col-lg-6">
        <label class="form-group" style="font-family:aleolight;font-size:14px;color:#000"> Estado del calendario</label>
        <select class="form-control" id="calen" name="calen"  style="cursor:pointer;">
            <option value="1">Abierto</option>
            <option value="0">Cerrado</option>
         
        </select>       
        </div>   
     
 </div>
    <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Fecha Inicio</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="in" name="in" value="<?php echo $this->calendario[0]['fecha_inicio']->format('d/m/Y');?>" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>
      <div class="col-lg-6">    
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Fecha Final</label>           
      <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
          <input type='text' id="fi" name="fi" value="<?php echo $this->calendario[0]['fecha_fin']->format('d/m/Y');?>" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div> 
     
 </div> 
</form>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="hidden" id="id" value="<?php echo $this->calendario[0]['id'];?>">  
     <input type="button" value="Guardar" id="editar" class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />
   </div>          
   </div>  
</div>
