<div class="row col-sm-4 col-md-6 col-lg-9" style="margin-top: 10px;">
    <h3 style="font-family:robotoblack;font-size:23px;color:#777">Listar Calendario</h3>
    <br>
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
              
                <th style="font-family:aleolight;font-size:14px;color:#000">Año</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Periodo</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Fecha Inicio</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Fecha Final</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Acciones</th>
                
            </tr>
        </thead>
        <tfoot>
            <tr>
            
                <th style="font-family:aleolight;font-size:14px;color:#000">Año</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Periodo</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Fecha Inicio</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Fecha Final</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Acciones</th>
            </tr>
        </tfoot>
        <tbody>
           <?php foreach ($this->calendario as $calendario) {?> 
            <tr>
                <td><?php echo $calendario ['id_annio']['annio'];?></td>
                <td><?php echo $calendario ['id_periodo']['periodo'];?></td>
               <!-- <td><?php echo $calendario ['estado'];?></td> -->
                <td><?php echo $calendario ['fecha_inicio']->format('Y-m-d');?></td>
                <td><?php echo $calendario ['fecha_fin']->format('Y-m-d');?></td>
                <td><a href="/calendar/editarcalendar/id/<?php echo $calendario ['id'];?> "><i class="fa fa-pencil-square-o" style="font-size:18px;color:#337ab7;cursor:pointer;"></i></a>&nbsp;<a class="eliminar_calendario" data-calendario="<?php echo $calendario ['id'];?>" href="#"><i class="fa fa-trash" style="font-size:18px;color:#d9534f;cursor:pointer;"></i></a></td>
            </tr> 
            <?php }?>
        </tbody>
    </table>    
        </div> 

