
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Usuario de las Dependencias</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Usuario</div>   
<div class="panel-body">
<form id="usu" method="post">
<div class="row"> 
      <div class="col-lg-6">
      <div class="form-group">
      <label for="input" class="">Nombres</label>           
      <input type="text" class="form-control" id="nom" name="nom"> 
      </div>    
      </div> 
      <div class="col-lg-6">
      <div class="form-group">
      <label for="input" class="">Apellidos</label>           
      <input type="text" class="form-control"  id="ape" name="ape"> 
      </div>    
      </div>    
    </div>
    <br>
    <div class="row">
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Identificación</label>           
      <input type="text" class="form-control" id="ide" name="ide"> 
      </div>    
      </div>    
     <div class="col-lg-6">
     <div class="form-group">
     <label for="input" class="">Correo</label>           
      <input type="text" class="form-control" id="correo" name="correo"> 
      </div>    
      </div>    
     </div>
    <br>
    <div class="row">
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="">Usuario</label>           
      <input type="text" class="form-control"  id="usuario" name="usuario"> 
      </div>    
      </div>    
      <div class="col-lg-6"> 
      <div class="form-group">
      <!--Codigo Para encriptar -->
      <label for="input" class="">Contraseña</label>           
      <input type="password" class="form-control"  id="pass" name="pass"> 
      </div>    
      </div>    
      </div>
     <div class="row"> 
     <br> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label>Rol</label> 
      <select class="form-control" id="rol" name="rol" style="cursor:pointer;">
          <?php foreach ($this->roles as $roles) {?>
          <option  value="<?php echo $roles['id_rol'];?>"><?php echo $roles['nombre'];?></option> 
           <?php }?> 
       </select>
      </div>    
      </div> 
      </div> 
     
</form> 
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
    <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " />  
   </div>          
   </div>  
</div>
