
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Editar Usuario</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Usuario</div>   
<div class="panel-body">
<form id="usu" method="post">
<div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombres</label>           
      <input type="text" class="form-control" value="<?php echo $this->usuarios[0]['nombre'];?>" id="nom" name="nom"> 
      </div>    
      </div> 
 </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Apellidos</label>           
      <input type="text" class="form-control" value="<?php echo $this->usuarios[0]['apellidos']; ?>" id="ape" name="ape"> 
      </div>    
      </div>    
    </div> 
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Identificación</label>           
      <input type="text" class="form-control" value="<?php echo $this->usuarios[0]['identificacion']; ?>" id="ide" name="ide"> 
      </div>    
      </div>    
    </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Correo</label>           
      <input type="text" class="form-control" value="<?php echo $this->usuarios[0]['correo']; ?>" id="correo" name="correo"> 
      </div>    
      </div>    
    </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Usuario</label>           
      <input type="text" class="form-control" value="<?php echo $this->usuarios[0]['usuario']; ?>" id="usuario" name="usuario"> 
      </div>    
      </div>    
    </div>
    <br>
    
     <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Nombre del Programa</label> 
      <select class="form-control" id="programa" name="programa" data-programa="<?php echo $this->usuarios[0]['cod_programa']['id_programa'];?>" style="cursor:pointer;">
           <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?> 
       </select>
      </div>    
      </div> 
 </div> 
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Rol</label> 
      <select class="form-control" id="rol" name="rol" data-rol="<?php echo $this->usuarios[0]['id_rol']['id_rol']; ?>" style="cursor:pointer;">
          <?php foreach ($this->roles as $roles) {?>
          <option  value="<?php echo $roles['id_rol'];?>"><?php echo $roles['nombre'];?></option> 
           <?php }?> 
       </select>
      
      </div>    
      </div> 
 </div> 
     
</form> 
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
    <input type="hidden" id="id_usuario" value="<?php echo $this->usuarios[0]['id_usuario']; ?>">    
    <input type="button" id="editar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " />  
   </div>          
   </div>  
</div>
