<div class="row col-sm-4 col-md-6 col-lg-9" style="margin-top: 10px;">
 <h3 style="font-family:robotoblack;font-size:23px;color:#777">Listado de Usuarios </h3>
    <br>
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
              
                <th style="font-family:aleolight;font-size:14px;color:#000">Nombres</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Apellidos</th>
           <!-- <th>Identificación</th> -->
          <!--  <th>Correo</th> -->
                <th style="font-family:aleolight;font-size:14px;color:#000">Usuario</th> 
          <!--  <th>Contraseña</th> -->
                <th style="font-family:aleolight;font-size:14px;color:#000">Nombre Programa</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Rol</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Acciones</th>
                
            </tr>
        </thead>
        <tfoot>
            <tr>
            
                <th style="font-family:aleolight;font-size:14px;color:#000">Nombres</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Apellidos</th>
          <!--  <th>Identificación</th> -->
           <!-- <th>Correo</th> -->
                <th style="font-family:aleolight;font-size:14px;color:#000">Usuario</th>
           <!-- <th>Contraseña</th> -->
                <th style="font-family:aleolight;font-size:14px;color:#000">Nombre Programa</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Rol</th>
                <th style="font-family:aleolight;font-size:14px;color:#000">Acciones</th>
            </tr>
        </tfoot>
        <tbody>
           <?php foreach ($this->usuarios as $usuarios) {?> 
           <tr>
               <td><?php echo $usuarios['nombre']; ?></td>
               <td><?php echo $usuarios['apellidos']; ?></td>
          <!-- <td><?php echo $usuarios['identificacion']; ?></td> -->
          <!-- <td><?php echo $usuarios['correo']; ?></td> -->
               <td><?php echo $usuarios['usuario']; ?></td>
          <!-- <td><?php echo $usuarios['contrasena']; ?></td> -->
               <td><?php echo $usuarios['cod_progra_power']; ?></td>
               <td><?php echo $usuarios['id_rol']['nombre']; ?></td>
               <td><a href="/usuarios/editarusuario/id/<?php echo $usuarios['id_usuario']; ?>"><i class="fa fa-pencil-square-o" style="font-size:18px;color:#337ab7;cursor:pointer;"></i></a>&nbsp;<a class="eliminar_usuario" data-usuario="<?php echo $usuarios['id_usuario']; ?>" href="#"> <i class="fa fa-trash" style="font-size:18px;color:#d9534f;cursor:pointer;"></i></a>&nbsp;<a href="/usuarios/resetearusuario/id/<?php echo $usuarios['id_usuario'];?>"> <i class="fa fa-unlock" style="font-size:18px;color:#643b25;cursor:pointer;"></i></a></td>
            </tr> 
          <?php }?> 
          </tbody>
    </table>    
        </div> 