<div class="row col-sm-4 col-md-6 col-lg-9" style="margin-top: 10px;">
    <h3>Listado de Usuarios </h3>
    <br>
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
              
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Identificación</th>
                <th>Correo</th>
                <th>Usuario</th>
                <th>Contraseña</th>
                <th>Nombre Programa</th>
                <th>Rol</th>
                <th>Acciones</th>
                
            </tr>
        </thead>
        <tfoot>
            <tr>
            
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Identificación</th>
                <th>Correo</th>
                <th>Usuario</th>
                <th>Contraseña</th>
                <th>Nombre Programa</th>
                <th>Rol</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
           <?php foreach ($this->usuarios as $usuarios) {?> 
           <tr>
               <td><?php echo $usuarios['nombre']; ?></td>
               <td><?php echo $usuarios['apellidos']; ?></td>
               <td><?php echo $usuarios['identificacion']; ?></td>
               <td><?php echo $usuarios['correo']; ?></td>
               <td><?php echo $usuarios['usuario']; ?></td>
               <td><?php echo $usuarios['contrasena']; ?></td>
               <td><?php echo $usuarios['cod_programa']['nombre']; ?></td>
               <td><?php echo $usuarios['id_rol']['nombre']; ?></td>
               <td><a href="/usuarios/editarusuario/id/<?php echo $usuarios['id_usuario'];?>"><i class="fa fa-pencil-square-o" style="font-size:18px;color:#337ab7;cursor:pointer;"></i></a>&nbsp;<a class=""  href="#"> <i class="fa fa-trash" style="font-size:18px;color:#d9534f;cursor:pointer;"></i></a></td>
            </tr> 
          <?php }?> 
          </tbody>
    </table>    
        </div> 