
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Viaticos del Conducror</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Liquidación del Conductor</div>   
<div class="panel-body">
<form id="liqui">
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Combustible</label>           
      <input type="text" class="form-control" id="combu" name="combu"> 
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Peajes</label>           
      <input type="text" class="form-control" id="pea" name="pea"> 
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Viaticos</label>           
      <input type="text" class="form-control" id="via" name="via"> 
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Imprevisto</label>           
      <input type="text" class="form-control" id="impre" name="impre"> 
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Pagado la Práctica</label>           
      <select class="form-control" id="paga" name="paga" style="cursor:pointer;">
      <option>Carro Nuevo</option>
      <option>Carros Viejo</option>
      <option>Carro Bueno</option>   
    
       </select> 
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Legalizado</label>           
      <input type="text" class="form-control" id="pea" name="pea"> 
      </div>    
      </div> 
      </div> 
</form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
