
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Viaticos del Conductor</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Liquidación del Conductor</div>   
<div class="panel-body">
<form id="liqui">
     <div class="row">
      <div class="col-lg-6">     
      <div class="form-group">
      <label for="input" class="">Combustible</label>           
      <input type="text" class="form-control" id="combu" name="combu"> 
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Peajes</label>           
      <input type="text" class="form-control" id="pea" name="pea"> 
      </div>    
      </div>   
      </div> 
    <br>
     <div class="row">
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Viaticos</label>           
      <input type="text" class="form-control" id="via" name="via"> 
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Imprevisto</label>           
      <input type="text" class="form-control" id="impre" name="impre"> 
      </div>    
      </div>    
      </div> 
    <br>
     <div class="row"> 
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Pagada la Práctica</label>           
      <select class="form-control" id="paga" name="paga" style="cursor:pointer;">
      <option>Trámite</option>
      <option>Pagado</option>
      <option>cancelado la Práctica</option>   
      </select> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Legalizado</label>           
      <select class="form-control" id="lega" name="lega" style="cursor:pointer;">
      <option>Pago Realizado</option>
      <option>Pago Sin Realizar</option>  
      </select>
      </div>    
      </div>    
      </div> 
       <br>
     <div class="row"> 
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Fecha Pago</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="pa" name="pa" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Fecha Legalizado</label>           
       <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
      <input type='text' id="le" name="le" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div>    
      </div> 
      <br>
     <div class="row">
       <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Conductor</label>           
      <select class="form-control" id="condu" name="condu" style="cursor:pointer;">
       <?php foreach ($this->conductor as $conductor) {?>  
          <option  value="<?php echo $conductor['id_conductor'];?>"><?php echo $conductor['id_conductor']['nombre'];?><?php echo $conductor['nombre'];?> <?php echo $conductor['apellido'];?></option>
         <?php }?> 
      </select> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Ruta</label>           
      <select class="form-control" id="ru" name="ru" style="cursor:pointer;">
      <?php foreach ($this->programacion as $programacion) {?>  
          <option  value="<?php echo $programacion['codigo_prog'];?>"><?php echo $programacion['recorrido'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row"> 
       <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Fecha Salida</label>           
      <select class="form-control" id="sali" name="sali" style="cursor:pointer;">
      <?php foreach ($this->programacion as $programacion) {?>  
          <option  value="<?php echo $programacion['codigo_prog'];?>"><?php echo $programacion['fecha_salida']->format('Y-m-d h:i:s');?></option>
         <?php }?> 
      </select> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Fecha llegada</label>           
      <select class="form-control" id="llega" name="llega" style="cursor:pointer;">
       <?php foreach ($this->programacion as $programacion) {?>  
          <option  value="<?php echo $programacion['codigo_prog'];?>"><?php echo $programacion['fecha_llegada']->format('Y-m-d h:i:s');?></option>
         <?php }?> 
      </select>
      </div>    
      </div> 
      </div> 
    <br>
     <div class="row">
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Vehiculo</label>           
      <select class="form-control" id="veh" name="veh" style="cursor:pointer;">
       <?php foreach ($this->transporte as $transporte) {?>  
          <option  value="<?php echo $transporte['cod_transporte'];?>"><?php echo $transporte['cod_transporte']['placa'];?><?php echo $transporte['placa'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Docente</label>           
      <select class="form-control" id="docent" name="docent" style="cursor:pointer;">
       <?php foreach ($this->programacion as $programacion) {?>  
          <option  value="<?php echo $programacion['codigo_prog'];?>"><?php echo $programacion['codigo_prog']['cod_practica'];?><?php echo $programacion['cod_practica']['nom_solicitante'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div> 
     </div>   
      <br>
     <div class="row">
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Facultad</label>           
      <select class="form-control" id="fa" name="fa" style="cursor:pointer;">
      <?php foreach ($this->practicas as $practicas) {?>  
      <option  value="<?php echo $practicas['cod_practica'];?>"><?php echo $practicas['cod_practica']['id_facultad'];?><?php echo $practicas['id_facultad']['nombre'];?></option>
      <?php }?>
      </select> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Programa</label>           
      <select class="form-control" id="pr" name="pr" style="cursor:pointer;">
       <?php foreach ($this->practicas as $practicas) {?>  
      <option  value="<?php echo $practicas['cod_practica'];?>"><?php echo $practicas['cod_practica']['id_programa'];?><?php echo $practicas['id_programa']['nombre'];?></option>
      <?php }?>
      </select>
      </div>    
      </div> 
      </div> 
        <br>
     <div class="row">
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="">Pasajeros</label>           
      <select class="form-control" id="pasaje" name="pasaje" style="cursor:pointer;">
      <?php foreach ($this->programacion as $programacion) {?>  
      <option  value="<?php echo $programacion['codigo_prog'];?>"><?php echo $programacion['num_pasajeros'];?></option>
      <?php }?>   
      </select> 
      </div>    
      </div>
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="">Codigo Práctica</label>           
      <select class="form-control" id="co" name="co" style="cursor:pointer;">
       <?php foreach ($this->practica as $practica) {?>  
          <option  value="<?php echo $practica['cod_practica'];?>"><?php echo $practica['cod_practica'];?><?php echo $practica['cod_practica']['cod_practica'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div> 
      </div> 
      
</form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
       <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
