
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Agregar Viaticos del Conductor</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:18px;color:#777"> Datos de la Liquidación del Conductor</div>   
<div class="panel-body">
<form id="liqui">
     <div class="row">
      <div class="col-lg-6">     
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Combustible</label>           
      <input type="text" class="form-control" id="combu" name="combu"> 
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Peajes</label>           
      <input type="text" class="form-control" id="pea" name="pea"> 
      </div>    
      </div>   
      </div> 
    <br>
     <div class="row">
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Viaticos</label>           
      <input type="text" class="form-control" id="via" name="via"> 
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Imprevistos</label>           
      <input type="text" class="form-control" id="impre" name="impre"> 
      </div>    
      </div>    
      </div> 
    <br>
     <div class="row"> 
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Pagada la Práctica</label>           
      <select class="form-control" id="paga" name="paga" style="cursor:pointer;">
      <option>Trámite</option>
      <option>Pagado</option>
      <option>cancelada la Práctica</option>   
      </select> 
      </div>    
      </div>
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Fecha Pago</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
      <input type='text' id="pa" name="pa" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div> 
      </div> 
       <br>
     <div class="row"> 
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Legalizado</label>           
      <select class="form-control" id="lega" name="lega" style="cursor:pointer;">
      <option>Si</option>
      <option>No</option>  
      </select>
      </div>    
      </div> 
       <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Fecha Legalizado</label>           
       <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
      <input type='text' id="le" name="le" placeholder="DD/MM/AAAA" class="form-control calendario"  />
      <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
      </div>    
      </div> 
      </div>    
      </div>    
      </div> 
      <br>
     <div class="row">
       <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Asignar Conductor</label>           
      <select class="form-control" id="condu" name="condu" style="cursor:pointer;">
       <?php foreach ($this->conductor as $conductor) {?>  
       <option  value="<?php echo $conductor['id_conductor'];?>"><?php echo $conductor['id_conductor']['nombre'];?><?php echo $conductor['nombre'];?> <?php echo $conductor['apellido'];?></option>
       <?php }?> 
      </select> 
      </div>    
      </div>
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Asignar Vehiculo</label>           
      <select class="form-control" id="veh" name="veh" style="cursor:pointer;">
       <?php foreach ($this->transporte as $transporte) {?>  
          <option  value="<?php echo $transporte['cod_transporte'];?>"><?php echo $transporte['cod_transporte']['placa'];?><?php echo $transporte['placa'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div>
      </div>    
      <div class="row">
      <div class="col-lg-6">      
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Codigo de programación</label>           
      <select class="form-control" id="veh" name="veh" style="cursor:pointer;">
       <?php foreach ($this->transporte as $transporte) {?>  
          <option  value="<?php echo $transporte['cod_transporte'];?>"><?php echo $transporte['cod_transporte']['placa'];?><?php echo $transporte['placa'];?></option>
         <?php }?> 
      </select>
      </div>    
      </div>    
      </div>
</form>
 
</div>
</div>    
   <div class="row">
   <div class=" text-center">
   <input type="button" id="agregar" value="Guardar"  class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />  
   </div>          
   </div>  
</div>
