<div class="row col-sm-4 col-md-6 col-lg-9" style="margin-top: 10px;">
    <h3>Programación de las Prácticas</h3>
    <br>
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Ruta</th>
                <th>Facha salida</th>
                <th>Fecha llegada</th>
                <th>pasajeros</th>
                <th>Docente</th>
                <th>Codigo Programación</th>
                <th>Acciones</th>
                
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Ruta</th>
                <th>Facha salida</th>
                <th>Fecha llegada</th>
                <th>pasajeros</th>
                <th>Docente</th>
                <th>Codigo Programación</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
           <?php foreach ($this->programacion as $programacion) {?> 
            <tr>
                <td><?php echo $programacion ['recorrido'];?></td>
                <td><?php echo $programacion ['fecha_salida']->format('Y-m-d h:i:s');?></td>
                <td><?php echo $programacion ['fecha_llegada']->format('Y-m-d h:i:s');?></td>
                <td><?php echo $programacion ['num_pasajeros'];?></td>
                <td><?php echo $programacion ['cod_practica']['nom_solicitante'];?></td>
                <td><?php echo $programacion ['codigo_prog'];?></td>
                <td><a href="/liquiconductor/agregarliquiconductor/id/<?php echo $programacion ['codigo_prog'];?> "><i class="fa fa-pencil-square" style="font-size:18px;color:#5cb85c;cursor:pointer;"></i></a></td>
            </tr> 
            <?php }?>
        </tbody>
    </table>    
        </div> 