
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Programa</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Programa</div>   
<div class="panel-body">
<form id="pro">
<div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombre del Programa</label>           
      <input type="text" class="form-control" id="programa" name="programa"> 
      </div>    
      </div> 
 </div> 
 <div class="row">  
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
          <label for="input" class="">Nombre de la Facultad</label>
          <select id="facultad" name="facultad" class="form-control" style="cursor:pointer;">
        <?php foreach ($this->facultades as $facultad) {?>  
          <option  value="<?php echo $facultad['id_facultad'];?>"><?php echo $facultad['nombre'];?></option>
         <?php }?> 
         
       </select>
      </div>    
      </div> 
 </div>      
        
</form> 
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
    <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " />  
   </div>          
   </div>  
</div>
