
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Agregar Los Recursos Especiales</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:18px;color:#777"> Datos de los Recursos</div>   
<div class="panel-body">
<div class="row">    
    <form id="recur">
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Nombre del Recurso Especial</label>           
      <input type="text" class="form-control" id="recu" name="recu"> 
      </div>    
      </div> 
    </form>
 </div>  
</div>
</div>    
   <div class="row">
   <div class=" text-center">
   <input type="button" id="agregar" value="Guardar"  class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />  
   </div>          
   </div>  
</div>
