<div class="row col-sm-4 col-md-6 col-lg-9" style="margin-top: 10px;">
    <h3>Listar Recursos Especiales</h3>
    <br>
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
              
                <th>Nombre del Recurso Especial</th>
                <th>Acciones</th>
                
            </tr>
        </thead>
        <tfoot>
            <tr>
            
                <th>Nombre del Recurso Especial</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
           <?php foreach ($this->recursos as $recursos) {?> 
            <tr>
                <td><?php echo $recursos ['nombre'];?></td>
                <td><a href="/recurespeciales/editarrecurespeciales/id/<?php echo $recursos ['id_recursos'];?> "><i class="fa fa-pencil-square-o" style="font-size:18px;color:#337ab7;cursor:pointer;"></i></a>&nbsp;<a class="eliminar_recursos" data-recursos="<?php echo $recursos['id_recursos'];?>" href="#"><i class="fa fa-trash" style="font-size:18px;color:#d9534f;cursor:pointer;"></i></a></td>
            </tr> 
            <?php }?>
        </tbody>
    </table>    
        </div> 