
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8"> 
        
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href='/css/family.css' rel='stylesheet' type='text/css'>
         <link href='/css/font-face.css' rel='stylesheet' type='text/css'>
        <link href='/css/login.css' rel='stylesheet' type='text/css'>
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="shortcut icon" href="/img/logo.jpg"> 
        <title>login</title>
         </head>
        
    <body>
    <div class="container">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div class="row">
            <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title" align="center" style="font-family:aleobold;font-size:20px"><strong>Autenticación Sipa</strong></h3>
            </div>
           <div class="panel-body"  class='img-responsive'alt='imagen responsive'>
            <form id="log" >
            <div class="row">
              <div class="col-xs-offset-0 col-xs-12 form-group">
                  <label for="user" style="font-family:aleobold;font-size:18px;color:#3c763d" class="control-label">Usuario:</label>
              <input class="form-control text-center" id="user" name="user" type="text" style="font-family:aleobold;font-size:16px;color:#3c763d" placeholder=" Digite el Usuario"> 
               </div>
             <div class="col-xs-offset-0 col-xs-12 form-group ">
                 <label for="contrasena" style="font-family:aleobold;font-size:18px;color:#3c763d" class="control-label">Contraseña:</label>
                 <input class="form-control text-center" id="pass" name="pass" style="font-family:aleobold;font-size:16px;color:#3c763d"  type="password" placeholder="Digite la Contraseña">         
             </div>
               <div id="remember" class="col-xs-8 form-group">
                    <label style="font-family:aleobold;font-size:16px;color:#3c763d">
                        <input type="checkbox" value="remember-me"> Recuérdame
                    </label>
                </div>
             <div class="form-group">  
             <div class='col-xs-offset-4 col-sm-8' style='padding-top:5px'>
                 <button  id="acceder" class="btn btn-default btn-lg" style="font-family:aleobold;font-size:18px;color:#1d9d74">Acceder</button>
             </div>
             </div>        
             </div>
             </form> 
               <br>
               <a href="#" class="forgot-password" style="font-family:aleobold;font-size:16px;color:#1d9d74">
                Ha Olvidado la Contraseña?
            </a>  
             </div>    
                    
            </div>    
                    
            </div>    
                
            </div>     
          
        </div>
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="/autenticar/login.js"></script>
     <script src="/validacion/jquery.validate.min.js"></script>
    <script src="/validacion/localization/messages_es.min.js"></script>    
    </body>
    
   
</html>

