
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8"> 
        
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href='/css/family.css' rel='stylesheet' type='text/css'>
        <link href='/css/login.css' rel='stylesheet' type='text/css'>
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="shortcut icon" href="/img/logo.jpg"> 
        <title>login</title>
         </head>
        
    <body>
    <div class="container">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div class="row">
            <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default" >
            <div class="panel-heading">
                <h3 class="panel-title" align="center"><strong>Autenticación Sipa</strong></h3>
            </div>
           <div class="panel-body"  class='img-responsive'alt='imagen responsive'>
            <form id="log" >
            <div class="row">
              <div class="col-xs-8 form-group ">
              <label for="user" class="control-label">Usuario:</label>
              <input class="form-control" id="user" name="user" type="text" placeholder="Usuario" required/> 
               </div>
             <div class="col-xs-8 form-group ">
                 <label for="contrasena" class="control-label">Contraseña:</label>
                 <input class="form-control" id="pass" name="pass"  type="password" placeholder="contraseña" required/>         
             </div>
               <div id="remember" class="col-xs-8 form-group">
                    <label>
                        <input type="checkbox" value="remember-me"> Recuérdame
                    </label>
                </div>
             <div class="form-group">  
             <div class='col-xs-offset-3 col-sm-8' style='padding-top: 5px;'>
             <button  id="acceder" class="btn btn-primary ">Acceder</button>
             </div>
             </div>        
             </div>
             </form> 
               <br>
              <a href="#" class="forgot-password">
                Ha Olvidado la Contraseña?
            </a>  
             </div>    
                    
            </div>    
                    
            </div>    
                
            </div>     
          
        </div>
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="/autenticar/login.js"></script>
     <script src="/validacion/jquery.validate.min.js"></script>
    <script src="/validacion/localization/messages_es.min.js"></script>    
    </body>
    
   
</html>

