
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Agregar Servicio</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:18px;color:#777"> Datos de los Servicios</div>   
<div class="panel-body">
  <form id="ser">
    <div class="row"> 
      <div class="col-lg-6">  
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Tipo Servicio</label>           
      <select class="form-control" id="servi" name="servi" style="cursor:pointer;">
      <option>Bus Interno</option>
      <option>Bus Externo</option>
      </select>
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Valor</label>           
      <input type="text" class="form-control" id="valo" name="valo"> 
      </div>    
      </div>   
      </div> 
       <br>
      <div class="row">
      <div class="col-lg-6">  
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Codigo Programación</label> 
      <select class="form-control" id="codi" name="codi" style="cursor:pointer;">
      <?php foreach ($this->programacion as $programacion) {?>    
      <option value="<?php echo $programacion['codigo_prog'] ;?>"> <?php echo $programacion['codigo_prog'];?></option>
       <?php }?> 
      </select>
      </div>    
      </div>
      </div> 
    </form>
  
</div>
</div>    
   <div class="row">
   <div class=" text-center">
   <input type="button" id="agregar" value="Guardar"  class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />
    
     
   </div>          
   </div>  
</div>
