
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Editar Servicio</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de los Servicios</div>   
<div class="panel-body">
  <form id="ser">
    <div class="row">     
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Tipo Servicio</label>           
      <select class="form-control" value="<?php echo $this->servicios[0]['tipo'];?>" id="servi" name="servi" style="cursor:pointer;">
      <option>Bus Interno</option>
      <option>Bus Externo</option>
      </select>
      </div>    
      </div>
      </div> 
       <br>
      <div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Valor</label>           
      <input type="text" class="form-control" value="<?php echo $this->servicios[0]['valor'];?>"  id="valo" name="valo"> 
      </div>    
      </div> 
     </div> 
       <br>
        <div class="row">     
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Codigo Programación</label> 
      <select class="form-control" id="codi" name="codi" data-programacion="<?php echo $this->servicios[0]['codigo_prog']['codigo_prog'];?>" style="cursor:pointer;">
      <?php foreach ($this->programacion as $programacion) {?>    
      <option value="<?php echo $programacion['codigo_prog'] ;?>"> <?php echo $programacion['codigo_prog'];?></option>
       <?php }?> 
      </select>
      </div>    
      </div>
      </div> 
    </form>
  
</div>
</div>    
   <div class="row">
   <div class=" text-center">
    <input type="hidden" id="cod_servicio" value="<?php echo $this->servicios[0]['cod_servicio'];?>">  
    <input type="button" id="editar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
