<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sipa</title>

    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="" rel="stylesheet">
    <!--Logo en el navegador -->
    <link rel="shortcut icon" href="/img/logo.jpg">
     <!--Para Agregar Css -->
     <?php echo $this->headLink(); ?>

</head>

<body>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#practicas"> Prácticas Académicas Unicordoba</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <!-- /.navbar-collapse -->
            
      <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Prácticas <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="/practicas/agregarpractica"> <i class="glyphicon glyphicon-plus-sign" aria-hidden="true" style="font-size:15px;"> </i> Agregar</a></li>
          <li><a href="/practicas/listarpractica"> <i class="glyphicon glyphicon-list" aria-hidden="true" style="font-size:15px;"> </i> Listar</a></li>
          <li><a href="#"><i class="glyphicon glyphicon-zoom-in" aria-hidden="true" style="font-size:15px;"> </i> Buscar</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Logistica <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="/conductor"> <i class="glyphicon glyphicon-user" aria-hidden="true" style="font-size:15px;"> </i> Admin Logística </a></li>
          
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Financiera <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="/practicas/agregarpractica">Crear Práctica</a></li>
          <li><a href="/practicas/listarpractica">Listar Práctica</a></li>
          <li><a href="#">Buscar Práctica</a></li>
          </ul>
      </li>
         <li><a href="/logout"><i class="glyphicon glyphicon-user"></i> Salir</a></li>
    </ul>          
      </div>
        </div>
</nav>
  <div class="container-fluid" style="margin-top: 50px;">
      <div class="row">
      <div class="col-sm-3 col-md-3 col-lg-3">
      <div class="list-group">
    <div class="list-group"><a href="#SoftPc" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Facultades<div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftPc">
		<div class="woll">
			<div class="list-group ssilka">
                        <a href="/facultades/agregarfacultad" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/facultades/listarfacultad" class="list-group-item"><i class="fa fa-list"></i> Listar </a>      
                        </div>
		</div>
	</div>
	<a href="#SoftMobile" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Programas<div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftMobile">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/programas/agregarprograma" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/programas/listarprograma" class="list-group-item"><i class="fa fa-list"></i> Listar</a> 	
			</div>
		</div>
	</div>
	<a href="#WebDevelopment" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Materias<div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="WebDevelopment">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/asignaturas/agregarasignatura" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/asignaturas/listarasignatura" class="list-group-item"><i class="fa fa-list"></i> Listar</a> 	
			</div>
		</div>
	</div>
        
	<a href="#ArchiveBooks" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Usuarios <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveBooks">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/usuarios/agregarusuario" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/usuarios/listarusuario" class="list-group-item"><i class="fa fa-list"></i> Listar</a> 
                        <a href="/usuarios/nuevacontrasena" class="list-group-item"><i class="fa fa-unlock"></i> Reseter Contraseña</a> 
			</div>
		</div>
	</div>
	<a href="#ArchiveAudio" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Calendario Académico <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveAudio">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/calendar/agregarcalendar/" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/calendar/listarcalendar/" class="list-group-item"><i class="fa fa-list"></i> Listar</a> 	
			</div>
		</div>
	</div>
	<a href="#ArchiveVideo" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Liquidar Viaticos <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveVideo">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/Partirespos/agregarpartirespo" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Agregar Viaticos</a>
				<a href="#" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Listar Viaticos</a>
			</div>
		</div>
	</div>
	<a href="#paid_section" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Autorizar Prácticas <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="paid_section">
		<div class="woll" style="margin-bottom:15px;">
			<div class="list-group ssilka">
				<a href="#" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Создание сайта</a>
				<a href="#" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Ремонт Пк (онлайн)</a>
			</div>
		</div>
	</div>
        <a href="#rutas" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Rutas <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="rutas">
		<div class="woll" style="margin-bottom:15px;">
			<div class="list-group ssilka">
				<a href="/rutas/agregarruta" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Agregar Rutas</a>
				<a href="/rutas/listarruta" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Listar Rutas</a>
			</div>
		</div>
	</div>
        <a href="#Recursos" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Recursos Especiales<div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="Recursos">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/recurespeciales/agregarrecurespeciales" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="/recurespeciales/listarrecurespeciales" class="list-group-item"><i class="fa fa-list"></i> Listar</a> 	
			</div>
		</div>
	</div>
</div>
</div>    
      </div>
       
    <div class="col-lg-9">    
    <?php echo $this->layout()->content; ?>          
    </div>          
</div> 
  </div>
   

    <!-- Page Content -->
    <div class="container">
      
    </div>
    

    <!-- jQuery -->
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
   
    
    <?php echo $this->headScript(); ?>

 

</body>

</html>
   