<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sipa</title>

    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="" rel="stylesheet">
    <!--Logo en el navegador -->
    <link rel="shortcut icon" href="img/logo.jpg">
     <!--Para Agregar Css -->
     <?php echo $this->headLink(); ?>

</head>

<body>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#practicas"> Prácticas Académicas Unicordoba</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <!-- /.navbar-collapse -->
            
      <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Prácticas <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica"><i class="glyphicon glyphicon-plus-sign" aria-hidden="true" style="font-size:15px;"> </i> Agregar</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica"><i class="glyphicon glyphicon-list" aria-hidden="true" style="font-size:15px;"> </i> Listar</a></li>
          <li><a href="#"><i class="glyphicon glyphicon-zoom-in" aria-hidden="true" style="font-size:15px;"> </i> Buscar</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Logistica <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica">Crear Práctica</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica">Listar Práctica</a></li>
          <li><a href="#">Buscar Práctica</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Financiera <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica">Crear Práctica</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica">Listar Práctica</a></li>
          <li><a href="#">Buscar Práctica</a></li>
          </ul>
      </li>
         <li><a href="#"><i class="glyphicon glyphicon-user"></i> Salir</a></li>
    </ul>          
      </div>
        </div>
</nav>
        <div class="container">
        <form>
        <div class="row">
        <div class="col-xs-6 col-md-4">
           
        </div>
        <div class="col-xs-6 col-md-4">
         
        </div>
        </div>    
        </form>
        </div>

   

    <!-- Page Content -->
    <div class="container">
    <?php echo $this->layout()->content; ?>    
    </div>
    

    <!-- jQuery -->
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
   
    
    <?php echo $this->headScript(); ?>

 

</body>

</html>
   