<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sipa</title>

    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="" rel="stylesheet">
    <!--Logo en el navegador -->
    <link rel="shortcut icon" href="img/logo.jpg">
     <!--Para Agregar Css -->
     <?php echo $this->headLink(); ?>

</head>

<body>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#practicas"> Prácticas Académicas Unicordoba</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <!-- /.navbar-collapse -->
            
      <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Logistica <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
        <li><a href="/conductor"> <i class="glyphicon glyphicon-user" aria-hidden="true" style="font-size:15px;"> </i> Admin Logística </a></li>
        </ul>
      </li>
         <li><a href="#"><i class="glyphicon glyphicon-user"></i> Salir</a></li>
    </ul>          
      </div>
        </div>
</nav>
  <div class="container-fluid" style="margin-top: 50px;">
      <div class="row">
      <div class="col-sm-3 col-md-3 col-lg-3">
      <div class="list-group">
    <div class="list-group"><a href="#SoftPc" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Programación Práctica  <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftPc">
		<div class="woll">
			<div class="list-group ssilka">
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>     
			</div>
		</div>
	</div>
	<a href="#SoftMobile" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Conductor <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftMobile">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="/conductor/agregarconductor" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>	
			</div>
		</div>
	</div>
	<a href="#WebDevelopment" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Vehiculo <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="WebDevelopment">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="#" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>
			</div>
		</div>
	</div>
	<a href="#ArchiveBooks" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Liquidar Conductor <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveBooks">
		<div class="woll">
			<div class="list-group ssilka">
		        <a href="#" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>
			</div>
		</div>
	</div>
	<a href="#ArchiveAudio" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Архив аудио <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveAudio">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/audio/audio_koran" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Коран (аудио)</a>
				<a href="/audio/audio_akida" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Акида (аудио)</a>
				<a href="/audio/audio_manhaj" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Манхадж (аудио)</a>
				<a href="/audio/audio_fiqh" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Фикх (аудио)</a>
				<a href="/audio/audio_hadith" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Хадисы (аудио)</a>
				<a href="/audio/audio_arabic" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Арабский язык (аудио)</a>
				<a href="/audio/audio_beginner" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для начинающих (аудио)</a>
			</div>
		</div>
	</div>
	<a href="#ArchiveVideo" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Архив видео <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveVideo">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/video/islamic_video" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Исламский видео</a>
				<a href="/video/other_videos" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Разное видео</a>
			</div>
		</div>
	</div>
	<a href="#paid_section" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Платный раздел <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="paid_section">
		<div class="woll" style="margin-bottom:15px;">
			<div class="list-group ssilka">
				<a href="/paid_section/site_development" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Создание сайта</a>
				<a href="/paid_section/pc_repair" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Ремонт Пк (онлайн)</a>
			</div>
		</div>
	</div>
</div>
</div>    
      </div>
 <!--     <div class="col-lg-4"  style="background-color:#bbb">
        <h1>Bienvenidos</h1> 
        <p>Modulo de Lógistica.</p>
      </div>
      <div class="col-lg-4"  style="background-color:#ccc">
        <h1>Hola</h1> 
        <p>Esto es una prueba de bootstrap.</p>
      </div>
    </div> -->
      <div class="col-lg-9">    
      <?php echo $this->layout()->content; ?>          
      </div> 
</div> 

   

    <!-- Page Content -->
    <div class="container">
    
    </div>
    

    <!-- jQuery -->
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
   
    
    <?php echo $this->headScript(); ?>

 

</body>

</html>
   