<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sipa</title>

    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="" rel="stylesheet">
    <!--Logo en el navegador -->
    <link rel="shortcut icon" href="img/logo.jpg">
     <!--Para Agregar Css -->
     <?php echo $this->headLink(); ?>

</head>

<body>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#practicas"> Prácticas Académicas Unicordoba</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <!-- /.navbar-collapse -->
            
      <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Prácticas <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica"><i class="glyphicon glyphicon-plus-sign" aria-hidden="true" style="font-size:15px;"> </i> Agregar</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica"><i class="glyphicon glyphicon-list" aria-hidden="true" style="font-size:15px;"> </i> Listar</a></li>
          <li><a href="#"><i class="glyphicon glyphicon-zoom-in" aria-hidden="true" style="font-size:15px;"> </i> Buscar</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Logistica <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica">Crear Práctica</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica">Listar Práctica</a></li>
          <li><a href="#">Buscar Práctica</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Financiera <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="http://sipa.unicordoba.co/practicas/agregarpractica">Crear Práctica</a></li>
          <li><a href="http://sipa.unicordoba.co/practicas/listarpractica">Listar Práctica</a></li>
          <li><a href="#">Buscar Práctica</a></li>
          </ul>
      </li>
         <li><a href="#"><i class="glyphicon glyphicon-user"></i> Salir</a></li>
    </ul>          
      </div>
        </div>
</nav>
  <div class="container-fluid" style="margin-top: 50px;">
      <div class="row">
      <div class="col-lg-4">
      <div class="list-group">
    <div class="list-group"><a href="#SoftPc" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Программы для PC <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftPc">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/soft/cd-dvd" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> CD/DVD диски</a>
				<a href="/soft/audio-video" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Аудио/Видео</a>
				<a href="/soft/security" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Безопасность</a>
				<a href="/soft/internet" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Интернет</a>
				<a href="/soft/system" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Система</a>
				<a href="/soft/office" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Офис</a>
			</div>
		</div>
	</div>
	<a href="#SoftMobile" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Приложения для Mobile <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftMobile">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/mobile/smartfon" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для smartfon</a>
				<a href="/mobile/android" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для android</a>
				<a href="/mobile/ipod" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для ipod</a>
				<a href="/mobile/java" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для java</a>
			</div>
		</div>
	</div>
	<a href="#WebDevelopment" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Веб-разработка <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="WebDevelopment">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/web-development/joomla" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Joomla</a>
				<a href="/web-development/wordpress" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Wordpress</a>
				<a href="/web-development/dle" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> DataLife Engine</a>
				<a href="/web-development/torrentpier" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> TorrentPier</a>
				<a href="/web-development/other_cms" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Другие CMS</a>
			</div>
		</div>
	</div>
	<a href="#ArchiveBooks" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Архив книги <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveBooks">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/books/books_akida" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Акида (книга)</a>
				<a href="/books/books_manhaj" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Манхадж (книга)</a>
				<a href="/books/books_fiqh" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Фикх (книга)</a>
				<a href="/books/books_hadith" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Хадисы (книга)</a>
				<a href="/books/books_koran" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Коран (книга)</a>
				<a href="/books/books_arabic" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Арабский язык (книга)</a>
				<a href="/books/books_beginner" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для начинающих (книга)</a>
			</div>
		</div>
	</div>
	<a href="#ArchiveAudio" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Архив аудио <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveAudio">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/audio/audio_koran" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Коран (аудио)</a>
				<a href="/audio/audio_akida" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Акида (аудио)</a>
				<a href="/audio/audio_manhaj" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Манхадж (аудио)</a>
				<a href="/audio/audio_fiqh" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Фикх (аудио)</a>
				<a href="/audio/audio_hadith" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Хадисы (аудио)</a>
				<a href="/audio/audio_arabic" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Арабский язык (аудио)</a>
				<a href="/audio/audio_beginner" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Для начинающих (аудио)</a>
			</div>
		</div>
	</div>
	<a href="#ArchiveVideo" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Архив видео <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveVideo">
		<div class="woll">
			<div class="list-group ssilka">
				<a href="/video/islamic_video" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Исламский видео</a>
				<a href="/video/other_videos" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Разное видео</a>
			</div>
		</div>
	</div>
	<a href="#paid_section" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Платный раздел <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="paid_section">
		<div class="woll" style="margin-bottom:15px;">
			<div class="list-group ssilka">
				<a href="/paid_section/site_development" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Создание сайта</a>
				<a href="/paid_section/pc_repair" class="list-group-item"><i class="fa fa-long-arrow-right"></i> <i class="fa fa-folder-open-o"></i> Ремонт Пк (онлайн)</a>
			</div>
		</div>
	</div>
</div>
</div>    
      </div>
      <div class="col-lg-4"  style="background-color:#bbb">
        <h1>Hola</h1> 
        <p>Esto es una prueba de bootstrap.</p>
      </div>
      <div class="col-lg-4"  style="background-color:#ccc">
        <h1>Hola</h1> 
        <p>Esto es una prueba de bootstrap.</p>
      </div>
    </div>
</div> 

   

    <!-- Page Content -->
    <div class="container">
    <?php echo $this->layout()->content; ?>    
    </div>
    

    <!-- jQuery -->
    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
   
    
    <?php echo $this->headScript(); ?>

 

</body>

</html>
   