
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Agregar Asignatura</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:23px;color:#777"> Datos de la asigantura</div>   
<div class="panel-body">  
<form id="asigna">
<div class="row"> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:16px;color:#000">Nombre de la asignatura</label>           
      <input  type="text" class="form-control" id="asignatura" name="asignatura"> 
      </div>    
      </div> 
      <div class="col-lg-6">   
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:16px;color:#000">Codigo de la asignatura</label>           
      <input  type="text" class="form-control" id="codigo" name="codigo"> 
      </div>    
      </div>
 </div>  
    <div class="row">
        <br>
      <div class="col-lg-6">
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:16px;color:#000">Grupo</label>           
      <input  type="text" class="form-control" id="grupo" name="grupo"> 
      </div>    
      </div> 
      <div class="col-lg-6"> 
      <div class="form-group">
      <label style="font-family:aleolight;font-size:16px;color:#000">Nombre del Programa</label>    
      <select class="form-control" id="programa" name="programa" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
      </div>    
      </div>  
    </div>
 <div class="row"> 
     <br>
      <div class="col-lg-6">
      <div class="form-group">
      <label style="font-family:aleolight;font-size:16px;color:#000">Nombre de la facultad</label>    
      <select class="form-control" id="facultad" name="facultad" style="cursor:pointer;">
         <?php foreach ($this->facultad as $facultad) {?>
          <option  value="<?php echo $facultad['id_facultad'];?>"><?php echo $facultad['nombre']; ?></option>
         <?php }?>
       </select>
      </div>    
      </div> 
       <div class="col-lg-6"> 
      <div class="form-group">
      <label style="font-family:aleolight;font-size:16px;color:#000">Nombre de la Sede</label>    
      <select class="form-control" id="sede" name="sede" style="cursor:pointer;">
         <?php foreach ($this->sedes as $sedes) {?>
          <option  value="<?php echo $sedes['id_sede']; ?>"><?php echo $sedes['nombre']; ?></option>
         <?php }?> 
       </select>
      </div>    
      </div>
 </div> 
</form>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="button" value="Guardar" id="agregar" class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />
    
    
   </div>          
   </div>  
</div>
