
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Editar Asignatura</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la asigantura</div>   
<div class="panel-body">  
<form id="asigna">
 <div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombre de la asignatura</label>           
      <input  type="text" class="form-control" value="<?php echo $this->asignaturas[0]['nombre'];?>" id="asignatura" name="asignatura"> 
      </div>    
      </div> 
 </div>
 <div class="row"> 
     <br>
      <div class="form-group">
      <div class="col-lg-6"> 
      <label>Nombre del Programa</label>    
      <select class="form-control" id="programa" name="programa" data-asignatura="<?php echo $this->asignaturas[0]['cod_programa']['id_programa'];?>" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
      </div>    
      </div> 
 </div>     
</from>   
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
     <input type="hidden" id="cod_asignatura" value="<?php echo $this->asignaturas[0]['cod_asignatura'];?>">  
     <input type="button" id="editar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " /> 
     
   </div>          
   </div>  
</div>
