
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class="" style="font-family:robotoblack;font-size:23px;color:#777"> Agregar Conductor</h3>     
<br>
<div class="panel panel-success">  
<div class="panel-heading" style="font-family:robotoblack;font-size:18px;color:#777"> Datos del Conductor</div>   
<div class="panel-body">
<form id="con">
<div class="row"> 
      <div class="col-lg-6">
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Nombres</label>           
      <input type="text" class="form-control" id="nom" name="nom"> 
      </div>    
      </div> 
     <div class="col-lg-6">    
     <div class="form-group">
     <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Apellidos</label>           
      <input type="text" class="form-control"  id="ape" name="ape"> 
      </div>    
      </div>  
 </div>
    <br>
    <div class="row">
     <div class="col-lg-6">    
     <div class="form-group">
     <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Identificación</label>           
      <input type="text" class="form-control" id="ide" name="ide"> 
      </div>    
      </div>
      <div class="col-lg-6">    
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Telefono</label>           
      <input type="tel" class="form-control" id="tele" name="tele"> 
      </div>    
      </div>   
    </div>
    <br>
    <div class="row">
      <div class="col-lg-6">   
      <div class="form-group">
      <label for="input" class="" style="font-family:aleolight;font-size:14px;color:#000">Dirección</label>           
      <input type="text" class="form-control"  id="dir" name="dir"> 
      </div>    
      </div>    
    </div>
    <br>    
</form> 
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
    <input type="button" id="agregar" value="Guardar"  class="btn btn-default" style="font-family:aleobold;font-size:18px;color:#1d9d74" />
   </div>          
   </div>  
</div>

