
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Agregar Conductor</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos del Conductor</div>   
<div class="panel-body">
<form id="con">
<div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombres</label>           
      <input type="text" class="form-control" id="nom" name="nom"> 
      </div>    
      </div> 
 </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Apellidos</label>           
      <input type="text" class="form-control"  id="ape" name="ape"> 
      </div>    
      </div>    
    </div> 
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Identificación</label>           
      <input type="text" class="form-control" id="ide" name="ide"> 
      </div>    
      </div>    
    </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Telefono</label>           
      <input type="tel" class="form-control" id="tele" name="tele"> 
      </div>    
      </div>    
    </div>
    <br>
    <div class="row">
     <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Dirección</label>           
      <input type="text" class="form-control"  id="dir" name="dir"> 
      </div>    
      </div>    
    </div>
    <br>
     
</form> 
</div>
</div>    
   <div class="row espacio">
   <div class=" text-center">
    <input type="button" id="agregar" value="Guardar"  class="btn btn-default"  />
    <input type="button" value="Cancelar"  class="btn btn-danger " />  
   </div>          
   </div>  
</div>

