
<div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;">
<h3 class=""> Editar Facultad</h3>     
<br>
<div class="panel panel-default">  
<div class="panel-heading"> Datos de la Facultad</div>   
<div class="panel-body">
    <form id="fac">
     <div class="row">    
      <div class="form-group">
      <div class="col-lg-6">    
      <label for="input" class="">Nombre de la Facultad</label>           
      <input type="text" class="form-control" value="<?php echo $this->facultad[0]['nombre'];?>" id="facultad" name="facultad"> 
      </div>    
      </div> 
 </div>  
</div>
</div> 
   
     <div class="row espacio">
   <div class=" text-center">
     <!-- guardar datos  -->
     <input type="hidden" id="id_facultad" value="<?php echo $this->facultad[0]['id_facultad'];?>">  
     <input type="button"  value="Guardar" id="editar" class="btn btn-default"  />
    <input type="button" value="Cancelar" class="btn btn-danger " />  
    
        </div>          
        </div>    
    </form>

        
     
</div>
</div>
</div>