<?php

namespace App\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_Usuarios extends \Application_Model_Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setid_usuario($idusuario)
    {
        $this->__load();
        return parent::setid_usuario($idusuario);
    }

    public function setnombre($nom)
    {
        $this->__load();
        return parent::setnombre($nom);
    }

    public function setapellidos($ape)
    {
        $this->__load();
        return parent::setapellidos($ape);
    }

    public function setidentificacion($identi)
    {
        $this->__load();
        return parent::setidentificacion($identi);
    }

    public function setcorreo($cor)
    {
        $this->__load();
        return parent::setcorreo($cor);
    }

    public function setusuario($user)
    {
        $this->__load();
        return parent::setusuario($user);
    }

    public function setcontrasena($pass)
    {
        $this->__load();
        return parent::setcontrasena($pass);
    }

    public function setid_rol($rol)
    {
        $this->__load();
        return parent::setid_rol($rol);
    }

    public function setcod_programa($cod)
    {
        $this->__load();
        return parent::setcod_programa($cod);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_usuario', 'nombre', 'apellidos', 'identificacion', 'correo', 'usuario', 'contrasena', 'fecha_creacion', 'id_rol', 'cod_programa');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}