<?php

namespace App\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_Transporte extends \Application_Model_Transporte implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setplaca($pla)
    {
        $this->__load();
        return parent::setplaca($pla);
    }

    public function setdescripcion($des)
    {
        $this->__load();
        return parent::setdescripcion($des);
    }

    public function settipo_vehiculo($ti)
    {
        $this->__load();
        return parent::settipo_vehiculo($ti);
    }

    public function setestado_vehiculo($est)
    {
        $this->__load();
        return parent::setestado_vehiculo($est);
    }

    public function setcapacidad_pasajeros($capa)
    {
        $this->__load();
        return parent::setcapacidad_pasajeros($capa);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'cod_transporte', 'placa', 'descripcion', 'tipo_vehiculo', 'estado_vehiculo', 'capacidad_pasajeros', 'fecha_registro');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}