<?php

namespace App\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_Partirespos extends \Application_Model_Partirespos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setaux_estudiante($aux)
    {
        $this->__load();
        return parent::setaux_estudiante($aux);
    }

    public function settransporte_especial($tra)
    {
        $this->__load();
        return parent::settransporte_especial($tra);
    }

    public function setfecha_pago($fe)
    {
        $this->__load();
        return parent::setfecha_pago($fe);
    }

    public function setfecha_legalizado($lega)
    {
        $this->__load();
        return parent::setfecha_legalizado($lega);
    }

    public function setlegalizado($le)
    {
        $this->__load();
        return parent::setlegalizado($le);
    }

    public function setpagado($paga)
    {
        $this->__load();
        return parent::setpagado($paga);
    }

    public function setcodigo_prog($cod)
    {
        $this->__load();
        return parent::setcodigo_prog($cod);
    }

    public function setid_participante($par)
    {
        $this->__load();
        return parent::setid_participante($par);
    }

    public function setid_pro($pro)
    {
        $this->__load();
        return parent::setid_pro($pro);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_responsable', 'aux_estudiante', 'transporte_especial', 'fecha_pago', 'fecha_legalizado', 'fecha_modificacion', 'legalizado', 'pagado', 'codigo_prog', 'id_participante', 'id_pro');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}