<?php

namespace App\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_Liquiconductores extends \Application_Model_Liquiconductores implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setcombustible($com)
    {
        $this->__load();
        return parent::setcombustible($com);
    }

    public function setpeajes($pe)
    {
        $this->__load();
        return parent::setpeajes($pe);
    }

    public function setviaticos($via)
    {
        $this->__load();
        return parent::setviaticos($via);
    }

    public function setimprevistos($impre)
    {
        $this->__load();
        return parent::setimprevistos($impre);
    }

    public function setpagado($paga)
    {
        $this->__load();
        return parent::setpagado($paga);
    }

    public function setlegalizado($lega)
    {
        $this->__load();
        return parent::setlegalizado($lega);
    }

    public function setfecha_pago($fecha)
    {
        $this->__load();
        return parent::setfecha_pago($fecha);
    }

    public function setfecha_legalizado($fe)
    {
        $this->__load();
        return parent::setfecha_legalizado($fe);
    }

    public function setcodigo_prog($codi)
    {
        $this->__load();
        return parent::setcodigo_prog($codi);
    }

    public function setid_conductor($condu)
    {
        $this->__load();
        return parent::setid_conductor($condu);
    }

    public function setcod_practica($pra)
    {
        $this->__load();
        return parent::setcod_practica($pra);
    }

    public function setcod_transporte($tra)
    {
        $this->__load();
        return parent::setcod_transporte($tra);
    }

    public function setregistrado($regi)
    {
        $this->__load();
        return parent::setregistrado($regi);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'combustible', 'peajes', 'viaticos', 'imprevistos', 'pagado', 'legalizado', 'fecha_pago', 'fecha_legalizado', 'fecha_modificacion', 'registrado', 'codigo_prog', 'id_conductor', 'cod_practica', 'cod_transporte');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}