<!-- Evento de departamento -->
<?php
if($this->rol == 4){?>
<script>
$(function(){
    console.log("hola");
    $('#fac').triggerHandler('change');
   // $('#asigna').triggerHandler('change');
   // $('#gru').triggerHandler('change');
});

</script>
<?php } ?>
<br>
<br>
<br>
<style>.modal .modal-dialog{width:800px;padding: 20px}</style>
<div class="fuelux">
     <a href="/inicio/departamento">
        <button type="button"  class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left"></span> Inicio</button></a>   
         <br>
    <h2>CREACIÓN DE PRÁCTICAS ACADÉMICAS</h2> 
<div class="wizard" data-initialize="wizard" id="myWizard">   
<div class="steps-container">
	<ul class="steps">
		<li data-step="1" data-name="campaign" class="active">
			<span class="badge">1</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="2">
			<span class="badge">2</span>Paso
			<span class="chevron"></span>
		</li>
                <li data-step="3">
			<span class="badge">3</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="4" data-name="template">
			<span class="badge">4</span>Paso
			<span class="chevron"></span>
		</li>
	</ul>
</div>
<div class="actions">
	<button type="button" class="btn btn-default btn-prev">
		<span class="glyphicon glyphicon-arrow-left"></span>Atrás</button>
    <button type="button" class="btn btn-primary btn-next" id="final" data-last="Finalizar">Siguiente
		<span class="glyphicon glyphicon-arrow-right"></span>
	</button>
</div>
    <form id="pra">
    <div class="step-content">
<div class="step-pane active sample-pane alert" data-step="1">
	<div class="row">
        <h3 class="text-center"> Fechas de la convocatoria de las prácticas académicas</h3>
        <h4 class="text-center">Dentro de estas fechas podra ingresar las prácticas académicas</h4>
        <div class="row"> 
         <br>
        <div class="col-xs-6"> 
        <div class="form-group">
        <label for="input" class="">Fecha Inicio del calendario académico</label>           
        <div class='input-group date'   id='divMiCalendario' style="cursor:pointer;">
        <input type='text' id="ini" name="ini" value="<?php echo $this->calendario[0]['fecha_inicio']->format('d/m/Y');?>" class="form-control calendario" disabled />
        <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div> 
        </div>
        </div>
        <div class="col-xs-6">    
        <div class="form-group">
        <label for="input" class="">Fecha Final del calendario académico</label>           
        <div class='input-group date' id='divMiCalendario1' style="cursor:pointer;">
        <input type='text' id="fin" name="fin" value="<?php echo $this->calendario[0]['fecha_fin']->format('d/m/Y');?>" class="form-control calendario"  disabled/>
        <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>         
        </div>
        </div>       
        </div> 
        <br>
       <div class="col-xs-6">
        <div class="">
        <label>Calendario Activo para la creación de la práctica académica </label>
        <select class="form-control" id="cal" name="cal" style="cursor:pointer;" disabled>
         <?php foreach ($this->calendario as $calendario) {?>
            <option  value="<?php echo $calendario['id']['id_annio'];?>"><?php echo $calendario['id_annio']['annio']; ?>&nbsp;<?php echo $calendario['id_periodo']['periodo'];?></option>
         <?php }?>
        </select>       
        </div>       
        </div>
        <div class="form-group">
        <label>Nombre del Solicitante</label>
        <div class="col-xs-6">
        <select class="form-control" id="nombre" name="nombre" style="cursor:pointer;">
       <?php foreach ($this->docentes as $docentes) {?>
          <option  value="<?php echo $docentes['ape'];?><?php echo $docentes['nom'];?>"><?php echo htmlentities(utf8_encode($docentes['ape']));?><?php echo htmlentities(utf8_encode($docentes['nom']));?></option>
       <?php }?>
        </select> 
        </div>
        </div>     
           
        </div> 
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Facultad </label>
        <select class="form-control" id="fac" name="fac" style="cursor:pointer;">
         <?php foreach ($this->facultad as $datos) {?>
          <option  value="<?php echo $datos['id_facultad'];?>"><?php echo htmlentities(utf8_encode($datos['nombre']));?></option>
         <?php }?>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Departamento </label> 
        <select class="form-control" id="dep" name="dep" style="cursor:pointer;">
        <option  value=""></option>
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Programa  </label>
        <select class="form-control" id="pro" name="pro" style="cursor:pointer;">
          <option  value=""></option>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="form-group">
        <label class=""> Semestre </label> 
        <select class="form-control" id="sem" name="sem" style="cursor:pointer;">
        <option></option>
        
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Asignatura </label>
        <select class="form-control" id="asigna" name="asigna" style="cursor:pointer;">
        
          <option  value=""></option>
         
        </select>       
        </div>       
        </div>
        <div class="col-xs-3">
        <div class="">
        <label class="form-group"> Grupo </label>
        <select class="form-control" id="gru" name="gru" style="cursor:pointer;">
        <option  value=""></option> 
        </select>   
        </div>       
        </div> 
         <div class="col-xs-3">
        <div class="">
        <label class="form-group"> Número Estudiantes </label>
        <select class="form-control" id="num" name="num" style="cursor:pointer;">
        <option  value=""></option> 
        </select>   
        </div>       
        </div> 
        </div>
        <div class="row">
         <br>
         <br>
         <div class="col-xs-6">
        <div class="form-group">
        <label for="">Nombre de la Práctica</label>
        <input type="text" name="nom" class="form-control" id="nom">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
         </div>
         <div class="col-xs-6">
         <div class="form-group">
        <label for="">Tipo de Práctica</label>
        <select class="form-control" name="tipo" style="cursor:pointer;" id="tipo">
        <option>Practica de Campo</option>
        <option>Visitas empresariales</option>
        <option>Prácticas Externas de laboratorio</option>
        </select>
        <small id="emailHelp" class="form-text text-muted">Selecione un tipo de Práctica.</small>
        </div>     
         </div>
        </div> 
        <div class="row">
        <div class="form-group">
        <div class="text-center"> <label for="">Objetivos de la Práctica</label></div>
        <textarea class="form-control" name="obj" id="obj" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <div class="text-center"><label for="">Justificación de la Práctica</label></div>
        <textarea class="form-control" name="jus" id="jus" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <div class="text-center"><label for="">Actividades desarrolladas por el Docente</label></div>
        <textarea class="form-control" name="adoc" id="adoc" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <div class="text-center"> <label for="">Actividades desarrolladas por el Estudiante</label></div>
        <textarea class="form-control" name="est" id="est" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>     
	</div>
     <div class="step-pane sample-pane  alert" data-step="2">
     <div class="row"> 
      <div class="form-group">
          <h3 class="text-center">Fechas para la Programación de las Prácticas Académicas</h3>  
          <h4 class="text-center">Por Favor ingrese las fecha de salida y de llegada de las programaciones</h4>
          <br>
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Salida</label>           
      <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
        <input type='text' id="sal" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
       </div> 
      </div>
      <div class="col-lg-6">    
      <label for="input" class="">Fecha Llegada</label>           
     <div class='input-group date' id='divMiCalendario'>
        <input type='text' id="lle" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
     </div> 
      </div>    
      </div> 
     
      </div> 
         <br>
        <div class="row">
        <div class="col-lg-6">
        <div class="form-group">
        <label for="">Lugar del Encuentro</label>
        <input type="text" id="lug" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div>     
	</div>
	<div class="step-pane sample-pane  alert" data-step="3">
        <br>    
        <div class="row">
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>NoDías</th>
                <th>Recor</th>
                <th>De</th> 
                <th>Fecha Sal</th>
                <th>Lugar</th>
                <th>DíasPern</th>
                <th>FechaLleg</th>
                <th>Recur</th>
                <th>Doce.R</th>
                <th>Aux</th>
                <th>Ases</th>
                <th>Obs</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>NoDías</th>
                <th>Recor</th>
                <th>De</th> 
                <th>Fecha Sal</th>
                <th>Lugar</th>
                <th>DíasPern</th>
                <th>FechaLleg</th>
                <th>Recur</th>
                <th>Doce.R</th>
                <th>Aux</th>
                <th>Ases</th>
                <th>Obs</th>
                <th>Accion</th>
            </tr>
        </tfoot>
        <tbody>
           
        </tbody>
    </table>    
        </div> 
        <div id="form" class="hide" style="padding: 20px; ">
        <div class="row">
        <div class="form-group">
        <label for="">Recorrido por dia de la Práctica</label>
        <select class="form-control reco"  name="reco" style="cursor:pointer;">
         <?php foreach ($this->rutas as $rutas) {?>
          <option  value="<?php echo $rutas['cod_ruta'];?>"><?php echo $rutas['ruta'];?></option>
          <?php }?>
        </select>  
        </div>    
        </div>    
        <br>
         <div class="row">
        <div class="form-group">
        <label for="">Desplazamiento</label>
        <input type="text"  class="form-control despla">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div> 
        </div>
        <br>
        <div class="row">
        <div class="form-group"> 
        <div class="checkbox">
            <label><input type="checkbox" class="per"> Pernoctado</label>
        </div>
         
        </div>       
         </div>
         <br>
         <div class="row">
             <br>
        <div class="col-xs-6">
        <label class="form-group"> Docente Responsable </label>
        <select class="form-control docen" name="docen"  style="cursor:pointer;">
        <?php foreach ($this->participantes as $participantes) {?>    
            <option value="<?php echo $participantes['id_participante'];?>"><?php echo $participantes['nombre'];?></option>
         <?php }?>
        </select>       
        </div> 
        <div class="col-xs-3">
            <br>   
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Docente' data-toggle="modal" data-target="#myModal1" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel1">Digite el Nombre y la Cedula del Docente Responsable,  </h4>
         </div>
        <div class="modal-body"  style="text-align: center">
        <div class="form-group">
         <input type='text' placeholder="Digite el Nombre" id="doce" name="doce"/>
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="docente" name="docente"/> 
         <br>
         <br>
          <label>Nombre del Programa</label>    
      <select class="form-control" id="programa" name="programa" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
        </div>
         Esta Seguro de Agregar el Docente
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agregar" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>      
        </div>
         <br>
         <div class="row">
             <br>
        <div class="col-xs-6">
        <label class="form-group"> Auxiliares </label>
        <select class="form-control auxi" name="auxi"  style="cursor:pointer;">
        <?php foreach ($this->participantess as $participantess) {?>    
            <option value="<?php echo $participantess['id_participante'];?>"><?php echo $participantess['nombre'];?></option>
         <?php }?>
        </select>       
        </div>
        <div class="col-xs-3">
            <br>   
              
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Auxiliar' data-toggle="modal" data-target="#myModal2" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2">Digite el Nombre y la Cedula del Auxiliar,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text'  placeholder="Digite el Nombre" id="aux" name="aux"/> 
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="auxiliar" name="auxiliar"/> 
         <br>
         <br> 
      <label>Nombre del Programa</label>    
      <select class="form-control" id="program" name="program" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
        </div>
         Esta Seguro de Agregar el Auxiliar
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agrega" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>       
        </div> 
         <br>
          <div class="row">
            <br>   
        <div class="col-xs-6">
        <label class="form-group"> Asesores </label>
        <select class="form-control ases" name="ases"  style="cursor:pointer;">
         <?php foreach ($this->participante as $participante) {?>    
            <option value="<?php echo $participante['id_participante'];?>"><?php echo $participante['nombre'];?></option>
         <?php }?>
        </select>       
        </div> 
        <div class="col-xs-3">
            <br>   
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Asesor' data-toggle="modal" data-target="#myModal3" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel3">Digite el Nombre y la Cedula del Asesor,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text'  placeholder="Digite el Nombre" id="ase" name="ase"/>  
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="asesor" name="asesor"/>
         <br>
         <br>
          <label>Nombre del Programa</label>    
      <select class="form-control" id="progra" name="progra" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
         </div>
         Esta Seguro de Agregar el Asesor
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agre" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>     
        </div>    
         <br>
          <div class="row">
             <br>
        <div class="form-group">
        <label for="">Observaciones</label>
        <textarea class="form-control obs"  rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>   
        </div>     
        <input type="hidden" id="codigo_prog" value="">      
        </div>
	</div>
	<div class="step-pane sample-pane  alert" data-step="4">
         <div class="text-center">
             <h2>Resumen de las Prácticas Académica</h2> 
             <h4>Por Favor verifique antes de finalizar la Práctica</h4>
         </div>
        <div class="row">
      <div class="container col-sm-6 col-md-6 col-lg-6" style="margin-top: 20px;">
       <h4 class=""> Paso 1 Agregar Práctica</h4>     
       <br>
       <div class="panel panel-info">  
       <div class="panel-heading"> Datos de la Práctica</div>   
       <div class="panel-body">
       <div class="row">    
      <div class="form-group">
      <div class="col-lg-12">    
      <div class="tabla_datos">
                      <div class="panel panel-default item-tabla item-tabla-61">
                      <div class="panel-body">  
                      <table class="table">
                     
                          <tr>
                              <td>Calendario Académico</td>
                              <td id="rep_cal"></td>
                          </tr>
                           <tr>
                              <td>Nombre del docente solicitante</td>
                              <td id="rep_docente"></td>
                          </tr>
                           <tr>
                              <td>Asignatura</td>
                              <td id="rep_asig"></td>
                          </tr>
                          <tr>
                              <td>Grupo</td>
                              <td id="rep_gru"></td>
                          </tr>
                           <tr>
                              <td>Número Estudiantes</td>
                              <td id="rep_numest"></td>
                          </tr>
                           <tr>
                              <td>Nombre Práctica</td>
                              <td id="rep_nompr"></td>
                          </tr>
                          <tr>
                              <td>Objetivos </td>
                              <td id="rep_obj"></td>
                          </tr>
                          <tr>
                              <td>Justificación </td>
                              <td id="rep_just"></td>
                          </tr>
                          <tr>
                              <td>Actividades Docente</td>
                              <td id="rep_actdoc"></td>
                          </tr>
                          <tr>
                              <td>Actividades Estudiantes</td>
                              <td id="rep_actest"></td>
                          </tr>
                          <tr>
                              <td>Tipo Práctica</td>
                              <td id="rep_tipopr"></td>
                          </tr>
                         </table>
                        </div>
                          
                    </div>
        </div>           
      </div>    
      </div> 
       </div>  
       </div>
       </div>    
      </div>
       <div class="container col-sm-6 col-md-6 col-lg-6" style="margin-top: 20px;">
       <h4 class=""> Paso 2 Agregar Fechas de Programación </h4>     
       <br>
       <div class="panel panel-info">  
       <div class="panel-heading"> Datos Fecha y Lugar</div>   
       <div class="panel-body">
           <div class="panel panel-default item-tabla item-tabla-61">
                      <div class="panel-body">  
                      <table class="table">
                     
                          <tr>
                              <td>Fecha salida</td>
                              <td id="rep_fsal"></td>
                          </tr>
                           <tr>
                              <td>Fecha llegada</td>
                              <td id="rep_flleg"></td>
                          </tr>
                           <tr>
                              <td>Lugar</td>
                              <td id="rep_lugar"></td>
                          </tr>
                           
                          
                         </table>
                        </div>
                          
                    </div>
       </div>
       </div>    
      </div>      
        </div>
          
        <div class="row">
          <div class="container col-sm-6 col-md-6 col-lg-12" style="margin-top: 20px;">
       <h4 class=""> Paso 3 Agregar Programación</h4>     
       <br>
       <div class="panel panel-info">  
       <div class="panel-heading"> Datos de Programación</div>   
       <div class="panel-body">
           <div id="rep_tbl"></div>
       </div>
       </div>    
      </div>  
        </div>     
	</div>

</div>    
    </form>
  <!--Recursos Especiales -->
  <div class="hide" id="re" style="padding:20px;">
    <br>
         <div class="row">
        <div class="col-xs-6">
        <label class="center-block">Recursos Especiales</label>
        <label class="form-group"> Tipo</label>
        <select class="form-control tipo" style="cursor:pointer;">
         <?php foreach ($this->recursos as $recursos) {?>
          <option  value="<?php echo $recursos['id_recursos'];?>"><?php echo $recursos['nombre'];?></option>
          <?php }?>
        </select>    
        </div>
        <div class="col-xs-6">
         <br>
        <label class="form-group"> valor($)</label>
        <input class="form-control valor"  type="text">
        <small id="emailHelp" class="form-text text-muted"></small>     
        </div>    
        </div>
         <br>
        <div class="text-right">
         <input type='button' class="button btn btn-default rec"  value='Agregar Recurso'  />        
        </div>
         <br>
           <div class="row">
        <table class="display recurso" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>id Recurso</th>
                <th>Tipo de Recurso</th>
                <th>Valor</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>id Recurso</th>
                <th>Tipo de Recurso</th>
                <th>Valor</th>
                <th>Accion</th>
            </tr>
        </tfoot>
        <tbody>
           
        </tbody>
    </table>    
        </div>    
  </div>

</div>       
</div>     

<!--Implementación de Wizard -->
        
      