<br>
<br>
<br>

<div class="fuelux">
    <h2>CREACIÓN DE PRÁCTICAS ACADÉMICAS</h2> 
<div class="wizard" data-initialize="wizard" id="myWizard">   
<div class="steps-container">
	<ul class="steps">
		<li data-step="1" data-name="campaign" class="active">
			<span class="badge">1</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="2">
			<span class="badge">2</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="3" data-name="template">
			<span class="badge">3</span>Paso
			<span class="chevron"></span>
		</li>
	</ul>
</div>
<div class="actions">
	<button type="button" class="btn btn-default btn-prev">
		<span class="glyphicon glyphicon-arrow-left"></span>Atrás</button>
	<button type="button" class="btn btn-primary btn-next" data-last="Finalizar">Siguiente
		<span class="glyphicon glyphicon-arrow-right"></span>
	</button>
</div>
<div class="step-content">
	<div class="step-pane active sample-pane alert" data-step="1">
	<form class="" action="" method="post">
        <div class="row">
        <br>
        <br>   
        <div class="col-xs-4">
        <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
        <input type='text' id="txtFecha" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span id="calend" class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>    
        </div>
        <div class="col-xs-4">
        <div class="form-group">
        <label class="redio-inline"> Periodo
        <label class="redio-inline">
        <input type="radio" name="optradio"> I       
        </label>
        <label class="redio-inline">
        <input type="radio" name="optradio"> II       
        </label>
        </label>       
        </div>       
        </div>
     <!--   <div class="col-xs-4">
        <div class="form-inline">
        <label class=""> Estado </label>
        <select class="form-control" style="cursor:pointer;" class="input-medium" disabled="">
        <option>0</option>
        <option>1</option>
        </select>             
        </div>    
        </div>  -->
        </div> 
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Facultad </label>
        <select class="form-control" style="cursor:pointer;">
        <option>Ingenieria</option>
        <option>Medicina veterinaria Zootecnia</option>
        <option>Ciencias Básicas</option>
        <option>Ciencias Agrículas</option>
        <option>Educación y Ciencias Humanas</option>
        <option>Ciencias Económicas, Jurídicas y Administrativas</option>
        <option>Ciencias de la Salud</option>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Departamento </label> 
        <select class="form-control" style="cursor:pointer;">
        <option>Ingenieria Ambiental</option>
        <option>Medicina veterinaria Zootecnia</option>
        <option>Ciencias Básicas</option>
        <option>Ciencias Agrículas</option>
        <option>Educación y Ciencias Humanas</option>
        <option>Ciencias Económicas, Jurídicas y Administrativas</option>
        <option>Ciencias de la Salud</option>
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Programa  </label>
        <select class="form-control" style="cursor:pointer;">
        <option>Ingenieria Ambiental</option>
        <option>Medicina veterinaria Zootecnia</option>
        <option>Ciencias Básicas</option>
        <option>Ciencias Agrículas</option>
        <option>Educación y Ciencias Humanas</option>
        <option>Ciencias Económicas, Jurídicas y Administrativas</option>
        <option>Ciencias de la Salud</option>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="form-group">
        <label class=""> Semestre </label> 
        <select class="form-control" style="cursor:pointer;">
        <option>I</option>
        <option>II</option>
        <option>III</option>
        <option>IV</option>
        <option>V</option>
        <option>VI</option>
        <option>VII</option>
        <option>VIII</option>
        <option>IX</option>
        <option>X</option>
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Asignatura </label>
        <select class="form-control" style="cursor:pointer;">
        <option>Ecologia(Grupo1-Codigo 407236)</option>
        <option>Medicina veterinaria Zootecnia</option>
        <option>Ciencias Básicas</option>
        <option>Ciencias Agrículas</option>
        <option>Educación y Ciencias Humanas</option>
        <option>Ciencias Económicas, Jurídicas y Administrativas</option>
        <option>Ciencias de la Salud</option>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Número Estudiantes </label>
        <input class="form-control" type="text">    
        </div>       
        </div> 
        </div>
        <div class="row">
         <br>
         <br>
        <div class="form-group">
        <label for="">Nombre de la Práctica</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Tipo de Práctica</label>
        <select class="form-control" style="cursor:pointer;">
        <option>Practica de Campo</option>
        <option>Visitas empresariales</option>
        <option>Prácticas Externas de laboratorio</option>
        </select>
        <small id="emailHelp" class="form-text text-muted">Selecione un tipo de Práctica.</small>
        </div>
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Docente Responsable</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Auxiliares</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Asesores</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Objetivos de la Práctica</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Justificación de la Práctica</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Actividades desarrolladas por el Docente</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Actividades desarrolladas por el Estudiante</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>     
        </form>	
	</div>
	<div class="step-pane sample-pane bg-info alert" data-step="2">
	<form class="" action="" method="post">
        <div class="row">
         <br>
         <br>
        <div class="form-group">
        <label for="">Numero de Días</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Recorrido por dia de la Práctica</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Fecha de Salida</label>    
        <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
        <input type='text' id="txtFecha1" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>       
        </div>     
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Lugar Encuentro</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div> 
        </div>
        <div class="row">
        <label class="" value="option1"> Días Pernoctados</label>
        <br>
        <label>
         <input type="radio" name="optionsRadios" id="optionsRadios1" value="">
          Si
         </label>
            <br>  
          <label>
          <input type="radio" name="optionsRadios" id="optionsRadios1" value="" >
          No
         </label>  
         </div>    
        <div class="row">
        <div class="form-group " style="cursor:pointer;">
        <label for="">Fecha de Llegada</label>    
        <div class='input-group date' id='divMiCalendario'>
        <input type='text' id="txtFecha2" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>       
        </div>     
        </div> 
        <div class="row">
        <div class="col-xs-6">
        <label class="center-block">Recursos Especiales</label>
        <label class="form-group"> Tipo</label>
        <input class="form-control" type="text">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>     
        </div>
        <div class="col-xs-6">
         <br>
        <label class="form-group"> valor($)</label>
        <input class="form-control" type="text">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>     
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Observaciones</label>
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>
        <div class="text-right">
        <input type='button' class="button btn btn-default" value='Agregar' data-toggle="modal" data-target="#myModal" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar Práctica </h4>
        </div>
        <div class="modal-body" style="text-align: center">
         Esta Seguro de Agregar Práctica Académica
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>    
        </div> 
        <br>    
        <div class="row">
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>No Días</th>
                <th>Recorrido</th>
                <th>Fecha Salida</th>
                <th>Lugar</th>
                <th>Días Pernoc</th>
                <th>Fecha Llegada</th>
                <th>Tipo</th>
                <th>Valor($)</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>No Días</th>
                <th>Recorrido</th>
                <th>Fecha Salida</th>
                <th>Lugar</th>
                <th>Días Pernoc</th>
                <th>Fecha Llegada</th>
                <th>Tipo</th>
                <th>Valor($)</th>
            </tr>
        </tfoot>
        <tbody>
            <tr>
                <td>1</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>Si</td>
                <td>04/12/2016 06:00</td>
                <td>Material Campo</td>
                <td>$250.000</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>No</td>
                <td>04/12/2016 06:00</td>
                <td>Trans. Acuatico</td>
                <td>$320,800</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>Si</td>
                <td>04/12/2016 06:00</td>
                <td>Material Campo</td>
                <td>$170,750</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>No</td>
                <td>04/12/2016 06:00</td>
                <td>Trans. Acuatico</td>
                <td>$86,000</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>Si</td>
                <td>04/12/2016 06:00</td>
                <td>Material Campo</td>
                <td>$433,060</td>
            </tr>
            <tr>
                <td>6</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>No</td>
                <td>04/12/2016 06:00</td>
                <td>Trans. Acuatico</td>
                <td>$162,700</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Mtr-Lorica-Cipata-S.Antero</td>
                <td>30/11/2016 07:00</td>
                <td>Unicor</td>
                <td>Si</td>
                <td>04/12/2016 06:00</td>
                <td>Material Campo</td>
                <td>$137,500</td>
            </tr>   
        </tbody>
    </table>    
        </div>    
        </form>	
	</div>
	<div class="step-pane sample-pane bg-danger alert" data-step="3">
	<form class="" action="" method="post">
        <div class="row">
        <br>
        <br>
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Docente Solicitante</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div> 
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Jefe Departamento</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div>
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Decano de la Facultad</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div>    
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Vicerrector Académico</label>
        <input type="text" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>    
        </div>     
        </form>	
	</div>
</div>


</div>       
</div>     

<!--Implementación de Wizard -->
        
      