<br>
<br>
<br>

<div class="fuelux">
    <h2>EDITAR  PRÁCTICAS ACADÉMICAS</h2> 
<div class="wizard" data-initialize="wizard" id="myWizard">   
<div class="steps-container">
	<ul class="steps">
		<li data-step="1" data-name="campaign" class="active">
			<span class="badge">1</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="2">
			<span class="badge">2</span>Paso
			<span class="chevron"></span>
		</li>
		<li data-step="3" data-name="template">
			<span class="badge">3</span>Paso
			<span class="chevron"></span>
		</li>
	</ul>
</div>
<div class="actions">
	<button type="button" class="btn btn-default btn-prev">
		<span class="glyphicon glyphicon-arrow-left"></span>Atrás</button>
    <button type="button" class="btn btn-primary btn-next" id="final" data-last="Finalizar">Siguiente
		<span class="glyphicon glyphicon-arrow-right"></span>
	</button>
</div>
    <form id="pra">
    <div class="step-content">
<div class="step-pane active sample-pane alert" data-step="1">
  <input type="hidden" id="cod_practica" value="<?php echo $this->practicas[0]['cod_practica']; ?>"> 
	<div class="row">
        <br>
        <br>   
       
       <div class="col-xs-6">
        <div class="">
        <label> Calendario </label>
        <select class="form-control" id="cal" name="cal" data-calendario="<?php echo $this->practicas[0]['id_calendario']['id'];?>"  style="cursor:pointer;">
         <?php foreach ($this->calendario as $calendario) {?>
          <option  value="<?php echo $calendario['id'];?>"><?php echo $calendario['annio']; ?>&nbsp;<?php echo $calendario['periodo']; ?></option>
         <?php }?>
        </select>       
        </div>       
        </div>
        <div class="form-group">
        <label>Nombre del Solicitante</label>
        <div class="col-xs-6">
        <input type="text" class="form-control" value="<?php echo $this->practicas[0]['nom_solicitante']?>" id="nombre" name="nombre" placeholder="Nombre del Docente Solicitante">
        </div>
        </div>     
           
        </div> 
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Facultad </label>
        <select class="form-control" name="fac" style="cursor:pointer;">
         <?php foreach ($this->facultad as $facultad) {?>
          <option  value="<?php echo $facultad['id_facultad'];?>"><?php echo $facultad['nombre']; ?></option>
         <?php }?>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Departamento </label> 
        <select class="form-control" name="dep" style="cursor:pointer;">
         <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Programa  </label>
        <select class="form-control" name="pro" style="cursor:pointer;">
         <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="form-group">
        <label class=""> Semestre </label> 
        <select class="form-control"  name="sem" style="cursor:pointer;">
        <?php foreach ($this->practicas as $practicas) {?>  
        <option  value="<?php echo $practicas['semestre'];?>"><?php echo $practicas['semestre'];?></option>
        <?php }?>
        </select>       
        </div>       
        </div> 
        </div>
        <div class="row">
        <br>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Asignatura </label>
        <select class="form-control" name="asigna" style="cursor:pointer;">
         <?php foreach ($this->asignatura as $asignatura) {?>
          <option  value="<?php echo $asignatura['cod_asignatura'];?>"><?php echo $asignatura['nombre'];?></option>
          <?php }?>
        </select>       
        </div>       
        </div>
        <div class="col-xs-6">
        <div class="">
        <label class="form-group"> Número Estudiantes </label>
        <input class="form-control" value="<?php echo $this->practicas[0]['num_estudiantes']?>"  name="num" type="text">    
        </div>       
        </div> 
        </div>
        <div class="row">
         <br>
         <br>
        <div class="form-group">
        <label for="">Nombre de la Práctica</label>
        <input type="text" value="<?php echo $this->practicas[0]['nombre']?>"  name="nom" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Tipo de Práctica</label>
        <select class="form-control" name="tipo" style="cursor:pointer;">
        <?php foreach ($this->practicas as $practicas) {?>  
        <option  value="<?php echo $practicas['tipo_practica'];?>"><?php echo $practicas['tipo_practica'];?></option>
        <?php }?>
        </select>
        <small id="emailHelp" class="form-text text-muted">Selecione un tipo de Práctica.</small>
        </div>
        </div>
        
        <div class="row">
        <div class="form-group">
        <label for="">Objetivos de la Práctica</label>
        <textarea class="form-control"   name="obj" id="exampleTextarea" rows="3"><?php echo $this->practicas[0]['objetivo']?></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Justificación de la Práctica</label>
        <textarea class="form-control"  name="jus" id="exampleTextarea" rows="3"><?php echo $this->practicas[0]['justificacion']?></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Actividades desarrolladas por el Docente</label>
        <textarea class="form-control"  name="adoc" id="exampleTextarea" rows="3"><?php echo $this->practicas[0]['actividad_doc']?></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Actividades desarrolladas por el Estudiante</label>
        <textarea class="form-control"  name="est" id="exampleTextarea" rows="3"><?php echo $this->practicas[0]['actividad_est']?> </textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>     
	</div>
	<div class="step-pane sample-pane bg-info alert" data-step="2">
	
        <div class="row">
         <br>
         <br>
        <div class="form-group">
        <label for="">Numero de Días</label>
        <input type="text" id="num" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        <div class="row">
        <div class="form-group">
        <label for="">Recorrido por dia de la Práctica</label>
        <select class="form-control" id="reco" name="reco" style="cursor:pointer;">
         <?php foreach ($this->rutas as $rutas) {?>
          <option  value="<?php echo $rutas['cod_ruta'];?>"><?php echo $rutas['ruta'];?></option>
          <?php }?>
        </select>  
        </div>    
        </div>
         <div class="row">
        <div class="form-group">
        <label for="">Desplazamiento</label>
        <input type="text" id="despla" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div> 
        </div>    
        <div class="row">
        <div class="form-group">
        <label for="">Fecha de Salida</label>    
        <div class='input-group date' id='divMiCalendario' style="cursor:pointer;">
        <input type='text' id="sal" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>       
        </div>     
        </div> 
        <div class="row">
        <div class="form-group">
        <label for="">Lugar Encuentro</label>
        <input type="text" id="lug" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div> 
        </div>
        <div class="row">
        <div class="form-group">
        <label class=""> Días Pernoctados </label> 
        <select class="form-control" name="per" id="per" style="cursor:pointer;">
        <option>0</option>
        <option>0.5</option>
        <option>1.0</option>
        <option>1.5</option>
        <option>2.0</option>
        <option>2.5</option>
        <option>3.0</option>
        <option>3.5</option>
        <option>4.0</option>
        <option>4.5</option>
        <option>5.0</option>
        <option>5.5</option>
        <option>6.0</option>
        <option>6.5</option>
        <option>7.0</option>
        <option>7.5</option>
        <option>8.0</option>
        <option>8.5</option>
        <option>9.0</option>
        <option>9.5</option>
        <option>10</option>
        <option>10.5</option>
        <option>11.0</option>
        <option>11.5</option>
        <option>12.0</option>
        <option>12.5</option>
        <option>13.0</option>
        <option>13.5</option>
        <option>14.0</option>
        <option>14.5</option>
        <option>15.0</option>
        <option>15.5</option>
        <option>16.0</option>
        <option>16.5</option>
        <option>17.0</option>
        <option>17.5</option>
        <option>18.0</option>
        <option>18.5</option>
        <option>19.0</option>
        <option>19.5</option>
        <option>20.0</option>
        <option>20.5</option>
        <option>21.0</option>
        <option>21.5</option>
        <option>22.0</option>
        <option>22.5</option>
        <option>23.0</option>
        <option>23.5</option>
        <option>24.0</option>
        <option>25.5</option>
        <option>26.0</option>
        <option>26.5</option>
        <option>27.0</option>
        <option>27.5</option>
        <option>28.0</option>
        <option>28.5</option>
        <option>29.0</option>
        <option>29.5</option>
        <option>30.0</option>
        <option>30.5</option>
        </select>       
        </div>       
         
         </div>    
        <div class="row">
        <div class="form-group " style="cursor:pointer;">
        <label for="">Fecha de Llegada</label>    
        <div class='input-group date' id='divMiCalendario'>
        <input type='text' id="lle" placeholder="DD/MM/AAAA" class="form-control calendario"  />
        <div class="input-group-addon"><span class="glyphicon glyphicon-calendar calendarioboton"></span>
        </div>    
        </div>       
        </div>     
        </div> 
        <div class="row">
        <div class="col-xs-6">
        <label class="center-block">Recursos Especiales</label>
        <label class="form-group"> Tipo</label>
        <select class="form-control" id="tipo"  style="cursor:pointer;">
         <?php foreach ($this->recursos as $recursos) {?>
          <option  value="<?php echo $recursos['id_recursos'];?>"><?php echo $recursos['nombre'];?></option>
          <?php }?>
        </select>    
        </div>
        <div class="col-xs-6">
         <br>
        <label class="form-group"> valor($)</label>
        <input class="form-control" id="valor" type="text">
        <small id="emailHelp" class="form-text text-muted"></small>     
        </div>    
        </div>
            <br>    
        <div class="text-right">
         <input type='button' class="button btn btn-default" id="rec" value='Agregar Recurso'  />        
        </div>
        <br>    
        <div class="row">
        <table id="examplee" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>id Recurso</th>
                <th>Tipo de Recurso</th>
                <th>Valor</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>id Recurso</th>
                <th>Tipo de Recurso</th>
                <th>Valor</th>
                <th>Accion</th>
            </tr>
        </tfoot>
        <tbody>
           
        </tbody>
    </table>    
        </div>  
        <div class="row">
             <br>
        <div class="col-xs-6">
        <label class="form-group"> Docente Responsable </label>
        <select class="form-control" name="docen" id="docen" style="cursor:pointer;">
        <?php foreach ($this->participantes as $participantes) {?>    
            <option value="<?php echo $participantes['id_participante'];?>"><?php echo $participantes['nombre'];?></option>
         <?php }?>
        </select>       
        </div> 
        <div class="col-xs-3">
            <br>   
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Docente' data-toggle="modal" data-target="#myModal1" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel1">Digite el Nombre y la Cedula del Docente Responsable,  </h4>
         </div>
        <div class="modal-body"  style="text-align: center">
        <div class="form-group">
         <input type='text' placeholder="Digite el Nombre" id="doce" name="doce"/>
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="docente" name="docente"/> 
         <br>
         <br>
          <label>Nombre del Programa</label>    
      <select class="form-control" id="programa" name="programa" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
        </div>
         Esta Seguro de Agregar el Docente
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agregar" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>      
        </div>  
        <div class="row">
             <br>
        <div class="col-xs-6">
        <label class="form-group"> Auxiliares </label>
        <select class="form-control" name="auxi" id="auxi" style="cursor:pointer;">
        <?php foreach ($this->participantess as $participantess) {?>    
            <option value="<?php echo $participantess['id_participante'];?>"><?php echo $participantess['nombre'];?></option>
         <?php }?>
        </select>       
        </div>
        <div class="col-xs-3">
            <br>   
              
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Auxiliar' data-toggle="modal" data-target="#myModal2" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2">Digite el Nombre y la Cedula del Auxiliar,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text'  placeholder="Digite el Nombre" id="aux" name="aux"/> 
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="auxiliar" name="auxiliar"/> 
         <br>
         <br> 
      <label>Nombre del Programa</label>    
      <select class="form-control" id="program" name="program" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
        </div>
         Esta Seguro de Agregar el Auxiliar
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agrega" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>       
        </div> 
        <div class="row">
            <br>   
        <div class="col-xs-6">
        <label class="form-group"> Asesores </label>
        <select class="form-control" name="ases" id="ases" style="cursor:pointer;">
         <?php foreach ($this->participante as $participante) {?>    
            <option value="<?php echo $participante['id_participante'];?>"><?php echo $participante['nombre'];?></option>
         <?php }?>
        </select>       
        </div> 
        <div class="col-xs-3">
            <br>   
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Asesor' data-toggle="modal" data-target="#myModal3" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel3">Digite el Nombre y la Cedula del Asesor,  </h4>
         </div>
        <div class="modal-body" style="text-align: center">
        <div class="form-group">
         <input type='text'  placeholder="Digite el Nombre" id="ase" name="ase"/>  
         <br>
         <br>
         <input type='text' placeholder="Digite la Cedula" id="asesor" name="asesor"/>
         <br>
         <br>
          <label>Nombre del Programa</label>    
      <select class="form-control" id="progra" name="progra" style="cursor:pointer;">
          <?php foreach ($this->programas as $programas) {?>
          <option  value="<?php echo $programas['id_programa'];?>"><?php echo $programas['nombre'];?></option>
          <?php }?>
       </select>
         </div>
         Esta Seguro de Agregar el Asesor
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="agre" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>         
        </div>     
        </div>         
        <div class="row">
             <br>
        <div class="form-group">
        <label for="">Observaciones</label>
        <textarea class="form-control" id="obs" rows="3"></textarea>
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>
        <div class="text-right">
        <input type='button' class="button btn btn-default"  value='Agregar Programacion' data-toggle="modal" data-target="#myModal" onclick=""/>
        <!-- Modal --> 
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header" style="text-align: center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar Programación de la Práctica </h4>
        </div>
        <div class="modal-body" style="text-align: center">
         Esta Seguro de Agregar La Programación de la Práctica Académica
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cerrar </button>
        <button type="button" id="prog" data-dismiss="modal" class="btn btn-default"> Aceptar </button>
        </div>
        </div>
        </div>
        </div>
        </div>    
        </div> 
        <br>    
        <div class="row">
        <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>NoDías</th>
                <th>Recor</th>
                <th>De</th> 
                <th>Fecha Sal</th>
                <th>Lugar</th>
                <th>DíasPern</th>
                <th>FechaLleg</th>
                <th>Recur</th>
                <th>Doce.R</th>
                <th>Aux</th>
                <th>Ases</th>
                <th>Obs</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>NoDías</th>
                <th>Recor</th>
                <th>De</th> 
                <th>Fecha Sal</th>
                <th>Lugar</th>
                <th>DíasPern</th>
                <th>FechaLleg</th>
                <th>Recur</th>
                <th>Doce.R</th>
                <th>Aux</th>
                <th>Ases</th>
                <th>Obs</th>
                <th>Accion</th>
            </tr>
        </tfoot>
        <tbody>
           
        </tbody>
    </table>    
        </div>    
	</div>
	<div class="step-pane sample-pane bg-danger alert" data-step="3">
	
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Jefe Departamento</label>
        <input type="text" name="jefe" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div>
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Decano de la Facultad</label>
        <input type="text" name="dec" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>
        </div>    
        <div class="row">
        <div class="">
        <div class="form-group">
        <label for="">Nombre del Vicerrector Académico</label>
        <input type="text" name="vice" class="form-control">
        <small id="emailHelp" class="form-text text-muted">Diligencie los campos.</small>
        </div>    
        </div>    
        </div>     
	</div>

</div>    
    </form>


</div>       
</div>     

<!--Implementación de Wizard -->
        
      