<div class="container" style="margin-top: 48px;">
      <div class="row">
      <div class="col-sm-3 col-md-3 col-lg-3">
      <div class="list-group">
    <div class="list-group"><a href="#SoftPc" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Gestor Prácticas<div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftPc">
		<div class="woll">
			<div class="list-group ssilka">
                        <a href="/practicas/agregarpractica" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>     
			</div>
		</div>
	</div>
	<a href="#SoftMobile" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Programación Práctica <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="SoftMobile">
		<div class="woll">
			<div class="list-group ssilka">
		        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>	
			</div>
		</div>
	</div>
	<a href="#WebDevelopment" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Solicitar Modificación de Prácticas <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="WebDevelopment">
		<div class="woll">
			<div class="list-group ssilka">
			<a href="#" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar la Solicitud </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>
			</div>
		</div>
	</div>
	<a href="#ArchiveBooks" class="list-group-item" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-folder-o"></i> Generar Reportes de Prácticas <div style="margin-top:-2px;" class="pull-right"><i class="fa fa-sort-desc"></i></div></a>
	<div class="collapse" id="ArchiveBooks">
		<div class="woll">
			<div class="list-group ssilka">
		        <a href="#" class="list-group-item"><i class="fa fa-plus-circle"></i> Agregar </a>
                        <a href="#" class="list-group-item"><i class="fa fa-list"></i> Listar </a>
			</div>
		</div>
	</div>
</div>
</div>    
      </div>
            
    <div class="container col-sm-4 col-md-6 col-lg-9" style="margin-top: 20px;"> 
        <h3>Bienvenidos  al Sistemas de Prácticas Académicas "Sipa"</h3> 
    <br>
    <div class="panel panel-default">  
        <div class="panel-heading"><h4 class="lead text-center">Prácticas Académicas</h4>  </div>   
    <div class="panel-body">
    <div class="row">    
      <div class="form-group">
      <div class="col-lg-12 text-justify">    
      <p class= "lead">Son actividades académicas que utilizan como metodología de aprendizaje,
      acciones que vinculan al estudiante con la realidad profesional y que le permiten
      su participación en equipos de trabajo interdiciplinarios, vivencias en situaciones, 
      empresariales, transculturales, autogestoras, de asistencia técnica e investigativa. 
      </p>       
      </div>    
      </div> 
    </div>  
    </div>
    </div>    
    </div>
    </div> 
      
</div> 

